// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosEduMessage : DataPortable 
	{
		public const string st_title = "st_title";
		public const string st_msg = "st_msg";
		public const string dt_start = "dt_start";
		public const string dt_end = "dt_end";
		public const string id_mem = "id_mem";
		
		public DadosEduMessage() { }
		
		public void Clear()
		{
			set_st_title ( "" );
			set_st_msg ( "" );
			set_dt_start ( "" );
			set_dt_end ( "" );
			set_id_mem ( "" );
		}
		
		public DadosEduMessage ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_title ( port.getValue ( st_title ) );
			set_st_msg ( port.getValue ( st_msg ) );
			set_dt_start ( port.getValue ( dt_start ) );
			set_dt_end ( port.getValue ( dt_end ) );
			set_id_mem ( port.getValue ( id_mem ) );
		}
		
		public string get_st_title () { return getValue ( st_title ); }
		public string get_st_msg () { return getValue ( st_msg ); }
		public string get_dt_start () { return getValue ( dt_start ); }
		public string get_dt_end () { return getValue ( dt_end ); }
		public string get_id_mem () { return getValue ( id_mem ); }
		
		public void set_st_title ( string val ) { setValue ( st_title , val ); }
		public void set_st_msg ( string val ) { setValue ( st_msg , val ); }
		public void set_dt_start ( string val ) { setValue ( dt_start , val ); }
		public void set_dt_end ( string val ) { setValue ( dt_end , val ); }
		public void set_id_mem ( string val ) { setValue ( id_mem , val ); }
	}
}
