// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosFechamento : DataPortable 
	{
		public const string st_cartao = "st_cartao";
		public const string st_nsu = "st_nsu";
		public const string dt_trans = "dt_trans";
		public const string vr_valor = "vr_valor";
		public const string nu_parcela = "nu_parcela";
		public const string st_loja = "st_loja";
		public const string st_terminal = "st_terminal";
		public const string vr_repasse = "vr_repasse";
		public const string st_cnpj = "st_cnpj";
		public const string st_matricula = "st_matricula";
		public const string st_nome = "st_nome";
		
		public DadosFechamento() { }
		
		public void Clear()
		{
			set_st_cartao ( "" );
			set_st_nsu ( "" );
			set_dt_trans ( "" );
			set_vr_valor ( "" );
			set_nu_parcela ( "" );
			set_st_loja ( "" );
			set_st_terminal ( "" );
			set_vr_repasse ( "" );
			set_st_cnpj ( "" );
			set_st_matricula ( "" );
			set_st_nome ( "" );
		}
		
		public DadosFechamento ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_cartao ( port.getValue ( st_cartao ) );
			set_st_nsu ( port.getValue ( st_nsu ) );
			set_dt_trans ( port.getValue ( dt_trans ) );
			set_vr_valor ( port.getValue ( vr_valor ) );
			set_nu_parcela ( port.getValue ( nu_parcela ) );
			set_st_loja ( port.getValue ( st_loja ) );
			set_st_terminal ( port.getValue ( st_terminal ) );
			set_vr_repasse ( port.getValue ( vr_repasse ) );
			set_st_cnpj ( port.getValue ( st_cnpj ) );
			set_st_matricula ( port.getValue ( st_matricula ) );
			set_st_nome ( port.getValue ( st_nome ) );
		}
		
		public string get_st_cartao () { return getValue ( st_cartao ); }
		public string get_st_nsu () { return getValue ( st_nsu ); }
		public string get_dt_trans () { return getValue ( dt_trans ); }
		public string get_vr_valor () { return getValue ( vr_valor ); }
		public string get_nu_parcela () { return getValue ( nu_parcela ); }
		public string get_st_loja () { return getValue ( st_loja ); }
		public string get_st_terminal () { return getValue ( st_terminal ); }
		public string get_vr_repasse () { return getValue ( vr_repasse ); }
		public string get_st_cnpj () { return getValue ( st_cnpj ); }
		public string get_st_matricula () { return getValue ( st_matricula ); }
		public string get_st_nome () { return getValue ( st_nome ); }
		
		public void set_st_cartao ( string val ) { setValue ( st_cartao , val ); }
		public void set_st_nsu ( string val ) { setValue ( st_nsu , val ); }
		public void set_dt_trans ( string val ) { setValue ( dt_trans , val ); }
		public void set_vr_valor ( string val ) { setValue ( vr_valor , val ); }
		public void set_nu_parcela ( string val ) { setValue ( nu_parcela , val ); }
		public void set_st_loja ( string val ) { setValue ( st_loja , val ); }
		public void set_st_terminal ( string val ) { setValue ( st_terminal , val ); }
		public void set_vr_repasse ( string val ) { setValue ( vr_repasse , val ); }
		public void set_st_cnpj ( string val ) { setValue ( st_cnpj , val ); }
		public void set_st_matricula ( string val ) { setValue ( st_matricula , val ); }
		public void set_st_nome ( string val ) { setValue ( st_nome , val ); }
	}
}
