// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosEmpresa : DataPortable 
	{
		public const string st_empresa = "st_empresa";
		public const string nu_CNPJ = "nu_CNPJ";
		public const string st_fantasia = "st_fantasia";
		public const string st_social = "st_social";
		public const string st_endereco = "st_endereco";
		public const string st_cidade = "st_cidade";
		public const string st_estado = "st_estado";
		public const string nu_CEP = "nu_CEP";
		public const string nu_telefone = "nu_telefone";
		public const string nu_cartoes = "nu_cartoes";
		public const string nu_parcelas = "nu_parcelas";
		public const string vr_taxa = "vr_taxa";
		public const string vr_pontos = "vr_pontos";
		public const string nu_lojas = "nu_lojas";
		public const string tx_convenio = "tx_convenio";
		public const string nu_dias_convenio = "nu_dias_convenio";
		public const string nu_contaDeb = "nu_contaDeb";
		public const string vr_mensalidade = "vr_mensalidade";
		public const string vr_cartaoAtivo = "vr_cartaoAtivo";
		public const string nu_pctValor = "nu_pctValor";
		public const string vr_transacao = "vr_transacao";
		public const string vr_minimo = "vr_minimo";
		public const string nu_franquia = "nu_franquia";
		public const string nu_periodoFat = "nu_periodoFat";
		public const string nu_diaVenc = "nu_diaVenc";
		public const string tg_tipoCobranca = "tg_tipoCobranca";
		public const string nu_bancoFat = "nu_bancoFat";
		public const string tg_isento = "tg_isento";
		public const string st_obs = "st_obs";
        public const string st_homepage = "st_homepage";

		public const string st_banco = "st_banco";
		public const string st_ag = "st_ag";
		public const string st_conta = "st_conta";
		public const string tg_bloq = "tg_bloq";
		
		public DadosEmpresa() { }
		
		public void Clear()
		{
			set_st_empresa ( "" );
			set_nu_CNPJ ( "" );
			set_st_fantasia ( "" );
			set_st_social ( "" );
			set_st_endereco ( "" );
			set_st_cidade ( "" );
			set_st_estado ( "" );
			set_nu_CEP ( "" );
			set_nu_telefone ( "" );
			set_nu_cartoes ( "" );
			set_nu_parcelas ( "" );
			set_vr_taxa ( "" );
			set_vr_pontos ( "" );
			set_nu_lojas ( "" );
			set_tx_convenio ( "" );
			set_nu_dias_convenio ( "" );
			set_nu_contaDeb ( "" );
			set_vr_mensalidade ( "" );
			set_vr_cartaoAtivo ( "" );
			set_nu_pctValor ( "" );
			set_vr_transacao ( "" );
			set_vr_minimo ( "" );
			set_nu_franquia ( "" );
			set_nu_periodoFat ( "" );
			set_nu_diaVenc ( "" );
			set_tg_tipoCobranca ( "" );
			set_nu_bancoFat ( "" );
			set_tg_isento ( "" );
			set_st_obs ( "" );
            set_st_homepage( "" );
			set_st_banco ( "" );
			set_st_ag ( "" );
			set_st_conta ( "" );
			set_tg_bloq ( "" );
		}
		
		public DadosEmpresa ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_nu_CNPJ ( port.getValue ( nu_CNPJ ) );
			set_st_fantasia ( port.getValue ( st_fantasia ) );
			set_st_social ( port.getValue ( st_social ) );
			set_st_endereco ( port.getValue ( st_endereco ) );
			set_st_cidade ( port.getValue ( st_cidade ) );
			set_st_estado ( port.getValue ( st_estado ) );
			set_nu_CEP ( port.getValue ( nu_CEP ) );
			set_nu_telefone ( port.getValue ( nu_telefone ) );
			set_nu_cartoes ( port.getValue ( nu_cartoes ) );
			set_nu_parcelas ( port.getValue ( nu_parcelas ) );
			set_vr_taxa ( port.getValue ( vr_taxa ) );
			set_vr_pontos ( port.getValue ( vr_pontos ) );
			set_nu_lojas ( port.getValue ( nu_lojas ) );
			set_tx_convenio ( port.getValue ( tx_convenio ) );
			set_nu_dias_convenio ( port.getValue ( nu_dias_convenio ) );
			set_nu_contaDeb ( port.getValue ( nu_contaDeb ) );
			set_vr_mensalidade ( port.getValue ( vr_mensalidade ) );
			set_vr_cartaoAtivo ( port.getValue ( vr_cartaoAtivo ) );
			set_nu_pctValor ( port.getValue ( nu_pctValor ) );
			set_vr_transacao ( port.getValue ( vr_transacao ) );
			set_vr_minimo ( port.getValue ( vr_minimo ) );
			set_nu_franquia ( port.getValue ( nu_franquia ) );
			set_nu_periodoFat ( port.getValue ( nu_periodoFat ) );
			set_nu_diaVenc ( port.getValue ( nu_diaVenc ) );
			set_tg_tipoCobranca ( port.getValue ( tg_tipoCobranca ) );
			set_nu_bancoFat ( port.getValue ( nu_bancoFat ) );
			set_tg_isento ( port.getValue ( tg_isento ) );
			set_st_obs ( port.getValue ( st_obs ) );
            set_st_homepage(port.getValue(st_homepage));

			set_st_banco ( port.getValue ( st_banco ) );
			set_st_ag ( port.getValue ( st_ag ) );
			set_st_conta ( port.getValue ( st_conta ) );
			set_tg_bloq ( port.getValue ( tg_bloq ) );
		}
		
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_nu_CNPJ () { return getValue ( nu_CNPJ ); }
		public string get_st_fantasia () { return getValue ( st_fantasia ); }
		public string get_st_social () { return getValue ( st_social ); }
		public string get_st_endereco () { return getValue ( st_endereco ); }
		public string get_st_cidade () { return getValue ( st_cidade ); }
		public string get_st_estado () { return getValue ( st_estado ); }
		public string get_nu_CEP () { return getValue ( nu_CEP ); }
		public string get_nu_telefone () { return getValue ( nu_telefone ); }
		public string get_nu_cartoes () { return getValue ( nu_cartoes ); }
		public string get_nu_parcelas () { return getValue ( nu_parcelas ); }
		public string get_vr_taxa () { return getValue ( vr_taxa ); }
		public string get_vr_pontos () { return getValue ( vr_pontos ); }
		public string get_nu_lojas () { return getValue ( nu_lojas ); }
		public string get_tx_convenio () { return getValue ( tx_convenio ); }
		public string get_nu_dias_convenio () { return getValue ( nu_dias_convenio ); }
		public string get_nu_contaDeb () { return getValue ( nu_contaDeb ); }
		public string get_vr_mensalidade () { return getValue ( vr_mensalidade ); }
		public string get_vr_cartaoAtivo () { return getValue ( vr_cartaoAtivo ); }
		public string get_nu_pctValor () { return getValue ( nu_pctValor ); }
		public string get_vr_transacao () { return getValue ( vr_transacao ); }
		public string get_vr_minimo () { return getValue ( vr_minimo ); }
		public string get_nu_franquia () { return getValue ( nu_franquia ); }
		public string get_nu_periodoFat () { return getValue ( nu_periodoFat ); }
		public string get_nu_diaVenc () { return getValue ( nu_diaVenc ); }
		public string get_tg_tipoCobranca () { return getValue ( tg_tipoCobranca ); }
		public string get_nu_bancoFat () { return getValue ( nu_bancoFat ); }
		public string get_tg_isento () { return getValue ( tg_isento ); }
		public string get_st_obs () { return getValue ( st_obs ); }
        public string get_st_homepage() { return getValue(st_homepage); }

		public string get_st_banco () { return getValue ( st_banco ); }
		public string get_st_ag () { return getValue ( st_ag ); }
		public string get_st_conta () { return getValue ( st_conta ); }
		public string get_tg_bloq () { return getValue ( tg_bloq ); }
		
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_nu_CNPJ ( string val ) { setValue ( nu_CNPJ , val ); }
		public void set_st_fantasia ( string val ) { setValue ( st_fantasia , val ); }
		public void set_st_social ( string val ) { setValue ( st_social , val ); }
		public void set_st_endereco ( string val ) { setValue ( st_endereco , val ); }
		public void set_st_cidade ( string val ) { setValue ( st_cidade , val ); }
		public void set_st_estado ( string val ) { setValue ( st_estado , val ); }
		public void set_nu_CEP ( string val ) { setValue ( nu_CEP , val ); }
		public void set_nu_telefone ( string val ) { setValue ( nu_telefone , val ); }
		public void set_nu_cartoes ( string val ) { setValue ( nu_cartoes , val ); }
		public void set_nu_parcelas ( string val ) { setValue ( nu_parcelas , val ); }
		public void set_vr_taxa ( string val ) { setValue ( vr_taxa , val ); }
		public void set_vr_pontos ( string val ) { setValue ( vr_pontos , val ); }
		public void set_nu_lojas ( string val ) { setValue ( nu_lojas , val ); }
		public void set_tx_convenio ( string val ) { setValue ( tx_convenio , val ); }
		public void set_nu_dias_convenio ( string val ) { setValue ( nu_dias_convenio , val ); }
		public void set_nu_contaDeb ( string val ) { setValue ( nu_contaDeb , val ); }
		public void set_vr_mensalidade ( string val ) { setValue ( vr_mensalidade , val ); }
		public void set_vr_cartaoAtivo ( string val ) { setValue ( vr_cartaoAtivo , val ); }
		public void set_nu_pctValor ( string val ) { setValue ( nu_pctValor , val ); }
		public void set_vr_transacao ( string val ) { setValue ( vr_transacao , val ); }
		public void set_vr_minimo ( string val ) { setValue ( vr_minimo , val ); }
		public void set_nu_franquia ( string val ) { setValue ( nu_franquia , val ); }
		public void set_nu_periodoFat ( string val ) { setValue ( nu_periodoFat , val ); }
		public void set_nu_diaVenc ( string val ) { setValue ( nu_diaVenc , val ); }
		public void set_tg_tipoCobranca ( string val ) { setValue ( tg_tipoCobranca , val ); }
		public void set_nu_bancoFat ( string val ) { setValue ( nu_bancoFat , val ); }
		public void set_tg_isento ( string val ) { setValue ( tg_isento , val ); }
		public void set_st_obs ( string val ) { setValue ( st_obs , val ); }
        public void set_st_homepage(string val) { setValue(st_homepage, val); }
		public void set_st_banco ( string val ) { setValue ( st_banco , val ); }
		public void set_st_ag ( string val ) { setValue ( st_ag , val ); }
		public void set_st_conta ( string val ) { setValue ( st_conta , val ); }
		public void set_tg_bloq ( string val ) { setValue ( tg_bloq , val ); }
	}
}
