// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosCartaoEdu : DataPortable 
	{
		public const string st_aluno = "st_aluno";
		public const string vr_diario = "vr_diario";
		public const string vr_disp = "vr_disp";
		public const string vr_depot = "vr_depot";
		public const string st_cartao = "st_cartao";
		public const string vr_disp_virtual = "vr_disp_virtual";
		public const string vr_invest_virtual = "vr_invest_virtual";
		public const string nu_vrRank = "nu_vrRank";
		public const string tg_semanaToda = "tg_semanaToda";
		
		public DadosCartaoEdu() { }
		
		public void Clear()
		{
			set_st_aluno ( "" );
			set_vr_diario ( "" );
			set_vr_disp ( "" );
			set_vr_depot ( "" );
			set_st_cartao ( "" );
			set_vr_disp_virtual ( "" );
			set_vr_invest_virtual ( "" );
			set_nu_vrRank ( "" );
			set_tg_semanaToda ( "" );
		}
		
		public DadosCartaoEdu ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_aluno ( port.getValue ( st_aluno ) );
			set_vr_diario ( port.getValue ( vr_diario ) );
			set_vr_disp ( port.getValue ( vr_disp ) );
			set_vr_depot ( port.getValue ( vr_depot ) );
			set_st_cartao ( port.getValue ( st_cartao ) );
			set_vr_disp_virtual ( port.getValue ( vr_disp_virtual ) );
			set_vr_invest_virtual ( port.getValue ( vr_invest_virtual ) );
			set_nu_vrRank ( port.getValue ( nu_vrRank ) );
			set_tg_semanaToda ( port.getValue ( tg_semanaToda ) );
		}
		
		public string get_st_aluno () { return getValue ( st_aluno ); }
		public string get_vr_diario () { return getValue ( vr_diario ); }
		public string get_vr_disp () { return getValue ( vr_disp ); }
		public string get_vr_depot () { return getValue ( vr_depot ); }
		public string get_st_cartao () { return getValue ( st_cartao ); }
		public string get_vr_disp_virtual () { return getValue ( vr_disp_virtual ); }
		public string get_vr_invest_virtual () { return getValue ( vr_invest_virtual ); }
		public string get_nu_vrRank () { return getValue ( nu_vrRank ); }
		public string get_tg_semanaToda () { return getValue ( tg_semanaToda ); }
		
		public void set_st_aluno ( string val ) { setValue ( st_aluno , val ); }
		public void set_vr_diario ( string val ) { setValue ( vr_diario , val ); }
		public void set_vr_disp ( string val ) { setValue ( vr_disp , val ); }
		public void set_vr_depot ( string val ) { setValue ( vr_depot , val ); }
		public void set_st_cartao ( string val ) { setValue ( st_cartao , val ); }
		public void set_vr_disp_virtual ( string val ) { setValue ( vr_disp_virtual , val ); }
		public void set_vr_invest_virtual ( string val ) { setValue ( vr_invest_virtual , val ); }
		public void set_nu_vrRank ( string val ) { setValue ( nu_vrRank , val ); }
		public void set_tg_semanaToda ( string val ) { setValue ( tg_semanaToda , val ); }
	}
}
