// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosAdicionais : DataPortable 
	{
		public const string st_empresa = "st_empresa";
		public const string id_comoSoube = "id_comoSoube";
		public const string id_time = "id_time";
		public const string st_presenteado = "st_presenteado";
		public const string st_recado = "st_recado";
		public const string st_nome_aluno = "st_nome_aluno";
		public const string st_senha_resp = "st_senha_resp";
		
		public DadosAdicionais() { }
		
		public void Clear()
		{
			set_st_empresa ( "" );
			set_id_comoSoube ( "" );
			set_id_time ( "" );
			set_st_presenteado ( "" );
			set_st_recado ( "" );
			set_st_nome_aluno ( "" );
			set_st_senha_resp ( "" );
		}
		
		public DadosAdicionais ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_id_comoSoube ( port.getValue ( id_comoSoube ) );
			set_id_time ( port.getValue ( id_time ) );
			set_st_presenteado ( port.getValue ( st_presenteado ) );
			set_st_recado ( port.getValue ( st_recado ) );
			set_st_nome_aluno ( port.getValue ( st_nome_aluno ) );
			set_st_senha_resp ( port.getValue ( st_senha_resp ) );
		}
		
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_id_comoSoube () { return getValue ( id_comoSoube ); }
		public string get_id_time () { return getValue ( id_time ); }
		public string get_st_presenteado () { return getValue ( st_presenteado ); }
		public string get_st_recado () { return getValue ( st_recado ); }
		public string get_st_nome_aluno () { return getValue ( st_nome_aluno ); }
		public string get_st_senha_resp () { return getValue ( st_senha_resp ); }
		
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_id_comoSoube ( string val ) { setValue ( id_comoSoube , val ); }
		public void set_id_time ( string val ) { setValue ( id_time , val ); }
		public void set_st_presenteado ( string val ) { setValue ( st_presenteado , val ); }
		public void set_st_recado ( string val ) { setValue ( st_recado , val ); }
		public void set_st_nome_aluno ( string val ) { setValue ( st_nome_aluno , val ); }
		public void set_st_senha_resp ( string val ) { setValue ( st_senha_resp , val ); }
	}
}
