// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosMovEmpresaVirtual : DataPortable 
	{
		public const string st_nome = "st_nome";
		public const string vr_mov_fundo = "vr_mov_fundo";
		public const string vr_total = "vr_total";
		public const string vr_acoes = "vr_acoes";
		public const string vr_osc = "vr_osc";
		public const string vr_dia = "vr_dia";
		public const string dt_dia = "dt_dia";
		public const string vr_preco_medio = "vr_preco_medio";
		
		public DadosMovEmpresaVirtual() { }
		
		public void Clear()
		{
			set_st_nome ( "" );
			set_vr_mov_fundo ( "" );
			set_vr_total ( "" );
			set_vr_acoes ( "" );
			set_vr_osc ( "" );
			set_vr_dia ( "" );
			set_dt_dia ( "" );
			set_vr_preco_medio ( "" );
		}
		
		public DadosMovEmpresaVirtual ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_nome ( port.getValue ( st_nome ) );
			set_vr_mov_fundo ( port.getValue ( vr_mov_fundo ) );
			set_vr_total ( port.getValue ( vr_total ) );
			set_vr_acoes ( port.getValue ( vr_acoes ) );
			set_vr_osc ( port.getValue ( vr_osc ) );
			set_vr_dia ( port.getValue ( vr_dia ) );
			set_dt_dia ( port.getValue ( dt_dia ) );
			set_vr_preco_medio ( port.getValue ( vr_preco_medio ) );
		}
		
		public string get_st_nome () { return getValue ( st_nome ); }
		public string get_vr_mov_fundo () { return getValue ( vr_mov_fundo ); }
		public string get_vr_total () { return getValue ( vr_total ); }
		public string get_vr_acoes () { return getValue ( vr_acoes ); }
		public string get_vr_osc () { return getValue ( vr_osc ); }
		public string get_vr_dia () { return getValue ( vr_dia ); }
		public string get_dt_dia () { return getValue ( dt_dia ); }
		public string get_vr_preco_medio () { return getValue ( vr_preco_medio ); }
		
		public void set_st_nome ( string val ) { setValue ( st_nome , val ); }
		public void set_vr_mov_fundo ( string val ) { setValue ( vr_mov_fundo , val ); }
		public void set_vr_total ( string val ) { setValue ( vr_total , val ); }
		public void set_vr_acoes ( string val ) { setValue ( vr_acoes , val ); }
		public void set_vr_osc ( string val ) { setValue ( vr_osc , val ); }
		public void set_vr_dia ( string val ) { setValue ( vr_dia , val ); }
		public void set_dt_dia ( string val ) { setValue ( dt_dia , val ); }
		public void set_vr_preco_medio ( string val ) { setValue ( vr_preco_medio , val ); }
	}
}
