// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;

namespace SyCrafEngine
{
	public class TB_T_CARTAO
	{
		public const string Alias  = "T_Cartao";
		public const string serial = "2";

		public const string i_unique = "i_unique";
		public const string st_empresa = "st_empresa";
		public const string st_matricula = "st_matricula";
		public const string st_titularidade = "st_titularidade";
		public const string st_senha = "st_senha";
		public const string tg_tipoCartao = "tg_tipoCartao";
		public const string st_venctoCartao = "st_venctoCartao";
		public const string tg_status = "tg_status";
		public const string dt_utlPagto = "dt_utlPagto";
		public const string nu_senhaErrada = "nu_senhaErrada";
		public const string dt_inclusao = "dt_inclusao";
		public const string dt_bloqueio = "dt_bloqueio";
		public const string tg_motivoBloqueio = "tg_motivoBloqueio";
		public const string st_banco = "st_banco";
		public const string st_agencia = "st_agencia";
		public const string st_conta = "st_conta";
		public const string st_matriculaExtra = "st_matriculaExtra";
		public const string st_celCartao = "st_celCartao";
		public const string fk_dadosProprietario = "fk_dadosProprietario";
		public const string fk_infoAdicionais = "fk_infoAdicionais";
		public const string nu_viaCartao = "nu_viaCartao";
		public const string vr_limiteTotal = "vr_limiteTotal";
		public const string vr_limiteMensal = "vr_limiteMensal";
		public const string vr_limiteRotativo = "vr_limiteRotativo";
		public const string vr_extraCota = "vr_extraCota";
		public const string vr_educacional = "vr_educacional";
		public const string vr_disp_educacional = "vr_disp_educacional";
		public const string vr_edu_diario = "vr_edu_diario";
		public const string st_aluno = "st_aluno";
		public const string tg_emitido = "tg_emitido";
		public const string vr_edu_disp_virtual = "vr_edu_disp_virtual";
		public const string nu_rankVirtual = "nu_rankVirtual";
		public const string vr_edu_total_ranking = "vr_edu_total_ranking";
		public const string nu_webSenhaErrada = "nu_webSenhaErrada";
		public const string tg_semanaCompleta = "tg_semanaCompleta";
		public const string tg_excluido = "tg_excluido";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_empresa = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_matricula = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_titularidade = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_tipoCartao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_venctoCartao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_status = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_utlPagto = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_nu_senhaErrada = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_inclusao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_bloqueio = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_motivoBloqueio = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_banco = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_agencia = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_conta = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_matriculaExtra = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_celCartao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_dadosProprietario = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_infoAdicionais = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_viaCartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_limiteTotal = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_limiteMensal = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_limiteRotativo = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_extraCota = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_educacional = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_disp_educacional = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_edu_diario = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_aluno = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_emitido = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_edu_disp_virtual = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_rankVirtual = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_edu_total_ranking = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_webSenhaErrada = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_semanaCompleta = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_excluido = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_INFOADICIONAIS
	{
		public const string Alias  = "T_InfoAdicionais";
		public const string serial = "3";

		public const string i_unique = "i_unique";
		public const string st_codigo = "st_codigo";
		public const string st_empresaAfiliada = "st_empresaAfiliada";
		public const string st_presenteado = "st_presenteado";
		public const string st_recado = "st_recado";
		public const string dt_edu_nasc = "dt_edu_nasc";
		public const string st_edu_sexo = "st_edu_sexo";
		public const string st_edu_grau = "st_edu_grau";
		public const string st_edu_serie_semestre = "st_edu_serie_semestre";
		public const string st_edu_turma = "st_edu_turma";
		public const string st_edu_curso = "st_edu_curso";
		public const string dt_edu_atualizacao = "dt_edu_atualizacao";
		public const string st_empresa = "st_empresa";
		public const string st_matricula = "st_matricula";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_codigo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_empresaAfiliada = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_presenteado = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_recado = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_edu_nasc = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_edu_sexo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_edu_grau = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_edu_serie_semestre = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_edu_turma = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_edu_curso = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_edu_atualizacao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_empresa = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_matricula = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_PROPRIETARIO
	{
		public const string Alias  = "T_Proprietario";
		public const string serial = "4";

		public const string i_unique = "i_unique";
		public const string st_cpf = "st_cpf";
		public const string st_nome = "st_nome";
		public const string st_endereco = "st_endereco";
		public const string st_numero = "st_numero";
		public const string st_complemento = "st_complemento";
		public const string st_bairro = "st_bairro";
		public const string st_cidade = "st_cidade";
		public const string st_UF = "st_UF";
		public const string st_cep = "st_cep";
		public const string st_ddd = "st_ddd";
		public const string st_telefone = "st_telefone";
		public const string dt_nasc = "dt_nasc";
		public const string st_email = "st_email";
		public const string vr_renda = "vr_renda";
		public const string st_senhaEdu = "st_senhaEdu";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_cpf = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_endereco = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_numero = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_complemento = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_bairro = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_cidade = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_UF = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_cep = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_ddd = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_telefone = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_nasc = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_email = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_renda = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_senhaEdu = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_DEPENDENTE
	{
		public const string Alias  = "T_Dependente";
		public const string serial = "5";

		public const string i_unique = "i_unique";
		public const string nu_titularidade = "nu_titularidade";
		public const string st_nome = "st_nome";
		public const string fk_proprietario = "fk_proprietario";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_titularidade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_proprietario = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LINK_PROPRIETARIOCARTAO
	{
		public const string Alias  = "LINK_ProprietarioCartao";
		public const string serial = "6";

		public const string i_unique = "i_unique";
		public const string fk_cartao = "fk_cartao";
		public const string fk_proprietario = "fk_proprietario";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_proprietario = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_FUTEBOL
	{
		public const string Alias  = "T_Futebol";
		public const string serial = "7";

		public const string i_unique = "i_unique";
		public const string st_logotipo = "st_logotipo";
		public const string st_nome = "st_nome";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_logotipo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_PROFISSOES
	{
		public const string Alias  = "T_Profissoes";
		public const string serial = "8";

		public const string i_unique = "i_unique";
		public const string st_codigo = "st_codigo";
		public const string st_profissao = "st_profissao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_codigo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_profissao = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_COMOSOUBE
	{
		public const string Alias  = "T_ComoSoube";
		public const string serial = "9";

		public const string i_unique = "i_unique";
		public const string st_descricao = "st_descricao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_descricao = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_USUARIO
	{
		public const string Alias  = "T_Usuario";
		public const string serial = "10";

		public const string i_unique = "i_unique";
		public const string tg_nivel = "tg_nivel";
		public const string tg_logoff = "tg_logoff";
		public const string dt_trocaSenha = "dt_trocaSenha";
		public const string dt_ultUso = "dt_ultUso";
		public const string nu_senhaErrada = "nu_senhaErrada";
		public const string tg_trocaSenha = "tg_trocaSenha";
		public const string st_senha_1 = "st_senha_1";
		public const string st_senha_2 = "st_senha_2";
		public const string st_senha_3 = "st_senha_3";
		public const string st_senha_4 = "st_senha_4";
		public const string st_senha_5 = "st_senha_5";
		public const string st_empresa = "st_empresa";
		public const string st_senha = "st_senha";
		public const string tg_bloqueio = "tg_bloqueio";
		public const string st_nome = "st_nome";
		public const string fk_quiosque = "fk_quiosque";
		public const string tg_aviso = "tg_aviso";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_nivel = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_logoff = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_trocaSenha = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_ultUso = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_nu_senhaErrada = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_trocaSenha = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha_1 = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha_2 = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha_3 = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha_4 = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha_5 = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_empresa = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_senha = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_bloqueio = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_quiosque = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_aviso = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LINK_LOJAEMPRESA
	{
		public const string Alias  = "LINK_LojaEmpresa";
		public const string serial = "11";

		public const string i_unique = "i_unique";
		public const string fk_loja = "fk_loja";
		public const string fk_empresa = "fk_empresa";
		public const string tx_admin = "tx_admin";
		public const string nu_dias_repasse = "nu_dias_repasse";
		public const string st_ag = "st_ag";
		public const string st_conta = "st_conta";
		public const string st_banco = "st_banco";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tx_admin = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_dias_repasse = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_ag = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_conta = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_banco = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_LOJA
	{
		public const string Alias  = "T_Loja";
		public const string serial = "12";

		public const string i_unique = "i_unique";
		public const string nu_CNPJ = "nu_CNPJ";
		public const string st_nome = "st_nome";
		public const string st_social = "st_social";
		public const string st_endereco = "st_endereco";
		public const string st_enderecoInst = "st_enderecoInst";
		public const string nu_inscEst = "nu_inscEst";
		public const string st_cidade = "st_cidade";
		public const string st_estado = "st_estado";
		public const string nu_CEP = "nu_CEP";
		public const string nu_telefone = "nu_telefone";
		public const string nu_fax = "nu_fax";
		public const string st_contato = "st_contato";
		public const string vr_mensalidade = "vr_mensalidade";
		public const string nu_contaDeb = "nu_contaDeb";
		public const string st_obs = "st_obs";
		public const string st_loja = "st_loja";
		public const string tg_blocked = "tg_blocked";
		public const string nu_pctValor = "nu_pctValor";
		public const string vr_transacao = "vr_transacao";
		public const string vr_minimo = "vr_minimo";
		public const string nu_franquia = "nu_franquia";
		public const string nu_periodoFat = "nu_periodoFat";
		public const string nu_diavenc = "nu_diavenc";
		public const string tg_tipoCobranca = "tg_tipoCobranca";
		public const string nu_bancoFat = "nu_bancoFat";
		public const string tg_isentoFat = "tg_isentoFat";
		public const string st_senha = "st_senha";
		public const string tg_cancel = "tg_cancel";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_CNPJ = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_social = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_endereco = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_enderecoInst = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_inscEst = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_cidade = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_estado = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_CEP = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_telefone = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_fax = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_contato = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_mensalidade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_contaDeb = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_obs = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_loja = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_blocked = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_pctValor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_transacao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_minimo = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_franquia = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_periodoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_diavenc = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_tipoCobranca = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_bancoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_isentoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_senha = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_cancel = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_EMPRESA
	{
		public const string Alias  = "T_Empresa";
		public const string serial = "13";

		public const string i_unique = "i_unique";
		public const string st_empresa = "st_empresa";
		public const string nu_CNPJ = "nu_CNPJ";
		public const string st_fantasia = "st_fantasia";
		public const string st_social = "st_social";
		public const string st_endereco = "st_endereco";
		public const string st_cidade = "st_cidade";
		public const string st_estado = "st_estado";
		public const string nu_CEP = "nu_CEP";
		public const string nu_telefone = "nu_telefone";
		public const string nu_cartoes = "nu_cartoes";
		public const string nu_parcelas = "nu_parcelas";
		public const string tg_blocked = "tg_blocked";
		public const string fk_admin = "fk_admin";
		public const string nu_contaDeb = "nu_contaDeb";
		public const string vr_mensalidade = "vr_mensalidade";
		public const string nu_pctValor = "nu_pctValor";
		public const string vr_transacao = "vr_transacao";
		public const string vr_minimo = "vr_minimo";
		public const string nu_franquia = "nu_franquia";
		public const string nu_periodoFat = "nu_periodoFat";
		public const string nu_diaVenc = "nu_diaVenc";
		public const string tg_tipoCobranca = "tg_tipoCobranca";
		public const string nu_bancoFat = "nu_bancoFat";
		public const string vr_cartaoAtivo = "vr_cartaoAtivo";
		public const string tg_isentoFat = "tg_isentoFat";
		public const string st_obs = "st_obs";
        public const string st_homepage = "st_homepage";
		public const string tg_bloq = "tg_bloq";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_empresa = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_CNPJ = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_fantasia = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_social = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_endereco = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_cidade = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_estado = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_CEP = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_telefone = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_cartoes = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_parcelas = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_blocked = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_admin = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_contaDeb = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_mensalidade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_pctValor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_transacao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_minimo = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_franquia = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_periodoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_diaVenc = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_tipoCobranca = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_bancoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_cartaoAtivo = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_isentoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_obs = ENUM_SQL_UNIT.chartype;
        public const ENUM_SQL_UNIT type_st_homepage = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_bloq = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_TERMINAL
	{
		public const string Alias  = "T_Terminal";
		public const string serial = "14";

		public const string i_unique = "i_unique";
		public const string nu_terminal = "nu_terminal";
		public const string fk_loja = "fk_loja";
		public const string st_localizacao = "st_localizacao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_terminal = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_localizacao = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LOG_AUDIT
	{
		public const string Alias  = "LOG_Audit";
		public const string serial = "15";

		public const string i_unique = "i_unique";
		public const string fk_usuario = "fk_usuario";
		public const string tg_operacao = "tg_operacao";
		public const string dt_operacao = "dt_operacao";
		public const string st_observacao = "st_observacao";
		public const string fk_generic = "fk_generic";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_usuario = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_operacao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_operacao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_observacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_generic = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LOG_NSU
	{
		public const string Alias  = "LOG_NSU";
		public const string serial = "16";

		public const string i_unique = "i_unique";
		public const string dt_log = "dt_log";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_log = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_I_SCHEDULER
	{
		public const string Alias  = "I_Scheduler";
		public const string serial = "17";

		public const string i_unique = "i_unique";
		public const string st_job = "st_job";
		public const string tg_type = "tg_type";
		public const string dt_specific = "dt_specific";
		public const string st_daily_hhmm = "st_daily_hhmm";
		public const string st_weekly_dow = "st_weekly_dow";
		public const string st_weekly_hhmm = "st_weekly_hhmm";
		public const string nu_monthly_day = "nu_monthly_day";
		public const string st_monthly_hhmm = "st_monthly_hhmm";
		public const string dt_last = "dt_last";
		public const string tg_status = "tg_status";
		public const string dt_prev = "dt_prev";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_job = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_type = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_specific = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_daily_hhmm = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_weekly_dow = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_weekly_hhmm = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_monthly_day = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_monthly_hhmm = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_last = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_status = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_prev = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_LOG_TRANSACOES
	{
		public const string Alias  = "LOG_Transacoes";
		public const string serial = "18";

		public const string i_unique = "i_unique";
		public const string fk_terminal = "fk_terminal";
		public const string dt_transacao = "dt_transacao";
		public const string nu_nsu = "nu_nsu";
		public const string fk_empresa = "fk_empresa";
		public const string fk_cartao = "fk_cartao";
		public const string vr_total = "vr_total";
		public const string nu_parcelas = "nu_parcelas";
		public const string nu_cod_erro = "nu_cod_erro";
		public const string tg_confirmada = "tg_confirmada";
		public const string nu_nsuOrig = "nu_nsuOrig";
		public const string en_operacao = "en_operacao";
		public const string st_msg_transacao = "st_msg_transacao";
		public const string tg_contabil = "tg_contabil";
		public const string fk_loja = "fk_loja";
		public const string vr_saldo_disp = "vr_saldo_disp";
		public const string vr_saldo_disp_tot = "vr_saldo_disp_tot";
		public const string st_doc = "st_doc";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_terminal = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_transacao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_nu_nsu = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_total = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_parcelas = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_cod_erro = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_confirmada = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_nsuOrig = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_en_operacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_msg_transacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_contabil = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_saldo_disp = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_saldo_disp_tot = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_doc = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_PARCELAS
	{
		public const string Alias  = "T_Parcelas";
		public const string serial = "19";

		public const string i_unique = "i_unique";
		public const string nu_nsu = "nu_nsu";
		public const string fk_empresa = "fk_empresa";
		public const string fk_cartao = "fk_cartao";
		public const string dt_inclusao = "dt_inclusao";
		public const string nu_parcela = "nu_parcela";
		public const string vr_valor = "vr_valor";
		public const string nu_indice = "nu_indice";
		public const string tg_pago = "tg_pago";
		public const string fk_loja = "fk_loja";
		public const string nu_tot_parcelas = "nu_tot_parcelas";
		public const string fk_terminal = "fk_terminal";
		public const string fk_log_transacoes = "fk_log_transacoes";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_nsu = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_inclusao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_nu_parcela = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_indice = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_pago = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_tot_parcelas = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_terminal = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_log_transacoes = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_PAYFONE
	{
		public const string Alias  = "T_PayFone";
		public const string serial = "20";

		public const string i_unique = "i_unique";
		public const string st_telefone = "st_telefone";
		public const string tg_tipoCelular = "tg_tipoCelular";
		public const string fk_cartao = "fk_cartao";
		public const string fk_terminal = "fk_terminal";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_telefone = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_tipoCelular = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_terminal = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_PENDPAYFONE
	{
		public const string Alias  = "T_PendPayFone";
		public const string serial = "21";

		public const string i_unique = "i_unique";
		public const string fk_cartao = "fk_cartao";
		public const string fk_terminal = "fk_terminal";
		public const string nu_nsu = "nu_nsu";
		public const string vr_valor = "vr_valor";
		public const string dt_inclusao = "dt_inclusao";
		public const string en_situacao = "en_situacao";
		public const string fk_empresa = "fk_empresa";
		public const string fk_loja = "fk_loja";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_terminal = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_nsu = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_inclusao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_en_situacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LINK_PFATIVACAO
	{
		public const string Alias  = "LINK_PFAtivacao";
		public const string serial = "22";

		public const string i_unique = "i_unique";
		public const string fk_payfone = "fk_payfone";
		public const string dt_ativacao = "dt_ativacao";
		public const string st_ativacao = "st_ativacao";
		public const string tg_status = "tg_status";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_payfone = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_ativacao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_ativacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_status = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LINK_AGENDA
	{
		public const string Alias  = "LINK_Agenda";
		public const string serial = "23";

		public const string i_unique = "i_unique";
		public const string fk_schedule = "fk_schedule";
		public const string fk_empresa = "fk_empresa";
		public const string en_atividade = "en_atividade";
		public const string st_emp_afiliada = "st_emp_afiliada";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_schedule = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_en_atividade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_emp_afiliada = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LOG_FECHAMENTO
	{
		public const string Alias  = "LOG_Fechamento";
		public const string serial = "24";

		public const string i_unique = "i_unique";
		public const string st_mes = "st_mes";
		public const string st_ano = "st_ano";
		public const string vr_valor = "vr_valor";
		public const string dt_fechamento = "dt_fechamento";
		public const string fk_empresa = "fk_empresa";
		public const string fk_loja = "fk_loja";
		public const string fk_cartao = "fk_cartao";
		public const string fk_parcela = "fk_parcela";
		public const string dt_compra = "dt_compra";
		public const string nu_parcela = "nu_parcela";
		public const string st_cartao = "st_cartao";
		public const string st_afiliada = "st_afiliada";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_mes = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_ano = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_fechamento = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_parcela = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_compra = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_nu_parcela = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_cartao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_afiliada = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_I_BATCH
	{
		public const string Alias  = "I_Batch";
		public const string serial = "25";

		public const string i_unique = "i_unique";
		public const string st_archive = "st_archive";
		public const string dt_start = "dt_start";
		public const string dt_proc_start = "dt_proc_start";
		public const string dt_proc_end = "dt_proc_end";
		public const string tg_processed = "tg_processed";
		public const string tg_running = "tg_running";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_archive = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_start = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_proc_start = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_proc_end = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_processed = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_running = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_EDU_EMPRESAVIRTUAL
	{
		public const string Alias  = "T_Edu_EmpresaVirtual";
		public const string serial = "26";

		public const string i_unique = "i_unique";
		public const string st_nome = "st_nome";
		public const string st_codigo = "st_codigo";
		public const string vr_valorAcao = "vr_valorAcao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_codigo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_valorAcao = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_EDU_APLICACAOVIRTUAL
	{
		public const string Alias  = "T_Edu_AplicacaoVirtual";
		public const string serial = "27";

		public const string i_unique = "i_unique";
		public const string fk_cartao = "fk_cartao";
		public const string fk_empresaVirtual = "fk_empresaVirtual";
		public const string vr_aplicado = "vr_aplicado";
		public const string dt_aplic = "dt_aplic";
		public const string tg_neg = "tg_neg";
		public const string vr_fundo_hora = "vr_fundo_hora";
		public const string vr_preco_fundo = "vr_preco_fundo";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresaVirtual = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_aplicado = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_aplic = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_neg = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_fundo_hora = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_preco_fundo = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LOG_EDU_RENDIMENTOEMPRESA
	{
		public const string Alias  = "LOG_Edu_RendimentoEmpresa";
		public const string serial = "28";

		public const string i_unique = "i_unique";
		public const string fk_empresaVirtual = "fk_empresaVirtual";
		public const string vr_pct = "vr_pct";
		public const string dt_rend = "dt_rend";
		public const string tg_neg = "tg_neg";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresaVirtual = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_pct = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_rend = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_neg = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_T_EDU_FUNDOEMPRESA
	{
		public const string Alias  = "T_Edu_FundoEmpresa";
		public const string serial = "29";

		public const string i_unique = "i_unique";
		public const string fk_cartao = "fk_cartao";
		public const string fk_empresaVirtual = "fk_empresaVirtual";
		public const string vr_fundo = "vr_fundo";
		public const string dt_efetivo = "dt_efetivo";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresaVirtual = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_fundo = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_efetivo = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_LINK_EDU_FUNDOEMPRESA
	{
		public const string Alias  = "LINK_Edu_FundoEmpresa";
		public const string serial = "30";

		public const string i_unique = "i_unique";
		public const string fk_cartao = "fk_cartao";
		public const string fk_empresa = "fk_empresa";
		public const string vr_fundo = "vr_fundo";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_fundo = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_WEBBLOCK
	{
		public const string Alias  = "T_WebBlock";
		public const string serial = "31";

		public const string i_unique = "i_unique";
		public const string st_ip = "st_ip";
		public const string fk_cartao = "fk_cartao";
		public const string dt_expire = "dt_expire";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_ip = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_expire = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_T_FATURAMENTO
	{
		public const string Alias  = "T_Faturamento";
		public const string serial = "32";

		public const string i_unique = "i_unique";
		public const string fk_empresa = "fk_empresa";
		public const string fk_loja = "fk_loja";
		public const string vr_cobranca = "vr_cobranca";
		public const string dt_vencimento = "dt_vencimento";
		public const string dt_baixa = "dt_baixa";
		public const string tg_situacao = "tg_situacao";
		public const string tg_retBanco = "tg_retBanco";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_cobranca = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_vencimento = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_baixa = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_situacao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_retBanco = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_FATURAMENTODETALHES
	{
		public const string Alias  = "T_FaturamentoDetalhes";
		public const string serial = "33";

		public const string i_unique = "i_unique";
		public const string fk_fatura = "fk_fatura";
		public const string tg_tipoFat = "tg_tipoFat";
		public const string nu_quantidade = "nu_quantidade";
		public const string vr_cobranca = "vr_cobranca";
		public const string tg_desconto = "tg_desconto";
		public const string st_extras = "st_extras";
		public const string fk_empresa = "fk_empresa";
		public const string fk_loja = "fk_loja";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_fatura = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_tipoFat = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_quantidade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_cobranca = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_desconto = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_extras = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_RETCOBRANCA
	{
		public const string Alias  = "T_RetCobranca";
		public const string serial = "34";

		public const string i_unique = "i_unique";
		public const string nu_codBanco = "nu_codBanco";
		public const string nu_cod = "nu_cod";
		public const string tg_tipoCob = "tg_tipoCob";
		public const string st_codMsg = "st_codMsg";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_codBanco = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_cod = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_tipoCob = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_st_codMsg = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LOG_NSA
	{
		public const string Alias  = "LOG_NSA";
		public const string serial = "35";

		public const string i_unique = "i_unique";
		public const string dt_log = "dt_log";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_log = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_LOG_NS_FAT
	{
		public const string Alias  = "LOG_NS_FAT";
		public const string serial = "36";

		public const string i_unique = "i_unique";
		public const string dt_log = "dt_log";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_log = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_T_CHAMADO
	{
		public const string Alias  = "T_Chamado";
		public const string serial = "37";

		public const string i_unique = "i_unique";
		public const string fk_loja = "fk_loja";
		public const string tg_fechado = "tg_fechado";
		public const string fk_operador = "fk_operador";
		public const string nu_prioridade = "nu_prioridade";
		public const string nu_categoria = "nu_categoria";
		public const string dt_abertura = "dt_abertura";
		public const string dt_fechamento = "dt_fechamento";
		public const string st_motivo = "st_motivo";
		public const string tg_tecnico = "tg_tecnico";
		public const string fk_oper_criador = "fk_oper_criador";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_fechado = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_operador = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_prioridade = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_categoria = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_abertura = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_fechamento = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_st_motivo = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_tg_tecnico = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_oper_criador = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LOG_CHAMADO
	{
		public const string Alias  = "LOG_Chamado";
		public const string serial = "38";

		public const string i_unique = "i_unique";
		public const string fk_chamado = "fk_chamado";
		public const string fk_operador = "fk_operador";
		public const string st_solucao = "st_solucao";
		public const string dt_solucao = "dt_solucao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_chamado = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_operador = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_solucao = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_solucao = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_T_EXTRAGIFT
	{
		public const string Alias  = "T_ExtraGift";
		public const string serial = "39";

		public const string i_unique = "i_unique";
		public const string st_nome = "st_nome";
		public const string vr_valor = "vr_valor";
		public const string fk_empresa = "fk_empresa";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_QUIOSQUE
	{
		public const string Alias  = "T_Quiosque";
		public const string serial = "40";

		public const string i_unique = "i_unique";
		public const string fk_empresa = "fk_empresa";
		public const string st_nome = "st_nome";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LOG_VENDACARTAOGIFT
	{
		public const string Alias  = "LOG_VendaCartaoGift";
		public const string serial = "41";

		public const string i_unique = "i_unique";
		public const string fk_vendedor = "fk_vendedor";
		public const string fk_empresa = "fk_empresa";
		public const string fk_cartao = "fk_cartao";
		public const string tg_tipoPag = "tg_tipoPag";
		public const string dt_compra = "dt_compra";
		public const string tg_tipoCartao = "tg_tipoCartao";
		public const string st_cheque = "st_cheque";
		public const string nu_nsuCartao = "nu_nsuCartao";
		public const string vr_carga = "vr_carga";
		public const string tg_adesao = "tg_adesao";
		public const string st_codImpresso = "st_codImpresso";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_vendedor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_tipoPag = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_compra = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_tipoCartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_cheque = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_nu_nsuCartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_carga = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_adesao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_codImpresso = ENUM_SQL_UNIT.chartype;
	}
	
	public class TB_LOG_VENDAPRODUTOGIFT
	{
		public const string Alias  = "LOG_VendaProdutoGift";
		public const string serial = "42";

		public const string i_unique = "i_unique";
		public const string fk_vendaCartao = "fk_vendaCartao";
		public const string st_produto = "st_produto";
		public const string vr_valor = "vr_valor";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_vendaCartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_produto = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_CHEQUESGIFT
	{
		public const string Alias  = "T_ChequesGift";
		public const string serial = "43";

		public const string i_unique = "i_unique";
		public const string st_identificador = "st_identificador";
		public const string fk_cartao = "fk_cartao";
		public const string dt_efetiva = "dt_efetiva";
		public const string tg_compensado = "tg_compensado";
		public const string vr_valor = "vr_valor";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_identificador = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_efetiva = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_tg_compensado = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LOG_GIFTRANGES
	{
		public const string Alias  = "LOG_GiftRanges";
		public const string serial = "44";

		public const string i_unique = "i_unique";
		public const string fk_empresa = "fk_empresa";
		public const string nu_inicio = "nu_inicio";
		public const string nu_fim = "nu_fim";
		public const string dt_requisicao = "dt_requisicao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_inicio = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_nu_fim = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_requisicao = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_T_REPASSELOJA
	{
		public const string Alias  = "T_RepasseLoja";
		public const string serial = "45";

		public const string i_unique = "i_unique";
		public const string fk_loja = "fk_loja";
		public const string tg_opcao = "tg_opcao";
		public const string vr_valor = "vr_valor";
		public const string st_ident = "st_ident";
		public const string dt_efetiva = "dt_efetiva";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_loja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_tg_opcao = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_valor = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_ident = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_dt_efetiva = ENUM_SQL_UNIT.datetime;
	}
	
	public class TB_LINK_REPASSEPARCELA
	{
		public const string Alias  = "LINK_RepasseParcela";
		public const string serial = "46";

		public const string i_unique = "i_unique";
		public const string fk_repasseLoja = "fk_repasseLoja";
		public const string fk_parcela = "fk_parcela";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_repasseLoja = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_parcela = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_TST
	{
		public const string Alias  = "tst";
		public const string serial = "47";

		public const string i_unique = "i_unique";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_EMPRESAAFILIADA
	{
		public const string Alias  = "T_EmpresaAfiliada";
		public const string serial = "48";

		public const string i_unique = "i_unique";
		public const string st_nome = "st_nome";
		public const string fk_empresa = "fk_empresa";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_nome = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_BOLETOEDU
	{
		public const string Alias  = "T_BoletoEdu";
		public const string serial = "49";

		public const string i_unique = "i_unique";
		public const string dt_emissao = "dt_emissao";
		public const string vr_imediato = "vr_imediato";
		public const string vr_educacional = "vr_educacional";
		public const string fk_cartao = "fk_cartao";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_emissao = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_vr_imediato = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_vr_educacional = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_cartao = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_LINK_USUARIOTERMINAL
	{
		public const string Alias  = "LINK_UsuarioTerminal";
		public const string serial = "50";

		public const string i_unique = "i_unique";
		public const string fk_user = "fk_user";
		public const string fk_term = "fk_term";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_user = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_fk_term = ENUM_SQL_UNIT.inttype;
	}
	
	public class TB_T_MENSAGEMEDU
	{
		public const string Alias  = "T_MensagemEdu";
		public const string serial = "51";

		public const string i_unique = "i_unique";
		public const string st_mens = "st_mens";
		public const string fk_empresa = "fk_empresa";
		public const string dt_ini = "dt_ini";
		public const string dt_fim = "dt_fim";

		public const ENUM_SQL_UNIT type_i_unique = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_st_mens = ENUM_SQL_UNIT.chartype;
		public const ENUM_SQL_UNIT type_fk_empresa = ENUM_SQL_UNIT.inttype;
		public const ENUM_SQL_UNIT type_dt_ini = ENUM_SQL_UNIT.datetime;
		public const ENUM_SQL_UNIT type_dt_fim = ENUM_SQL_UNIT.datetime;
	}
}
