// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class LINK_ProprietarioCartao : Synchronization
	{
		private string i_unique = "0";
		private string fk_cartao = "0";
		private string fk_proprietario = "0";
		
		public int var_FieldCount = 3;
		
		public LINK_ProprietarioCartao ()
		{
			var_Serial = TB_LINK_PROPRIETARIOCARTAO.serial;
			var_Tablename = TB_LINK_PROPRIETARIOCARTAO.Alias;
		}
		
		public LINK_ProprietarioCartao ( Transaction trx )
		{
			AcquireTransaction ( ref trx );
			
			var_Serial = TB_LINK_PROPRIETARIOCARTAO.serial;
			var_Tablename = TB_LINK_PROPRIETARIOCARTAO.Alias;
			
			TraceLog ( var_Tablename + " serial : " + var_serialNumber);
		}
		
		public string exportNames()
		{
			return "fk_cartao,fk_proprietario";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + fk_cartao + str_field_sep + fk_proprietario;
		}
		
		public void Reset()
		{
			i_unique = "0";
			fk_cartao = "0";
			fk_proprietario = "0";
		
			ReleaseExclusive();
		}
		
		public void copy ( ref LINK_ProprietarioCartao cpy )
		{
			fk_cartao = cpy.fk_cartao;
			fk_proprietario = cpy.fk_proprietario;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_LINK_PROPRIETARIOCARTAO.i_unique );
			fk_cartao = row.GetField ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao );
			fk_proprietario = row.GetField ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario );
		}
		
		public bool synchronize_LINK_ProprietarioCartao ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "fk_cartao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao , fk_cartao , TB_LINK_PROPRIETARIOCARTAO.type_fk_cartao );
			if ( m_hshChangedFields [ "fk_proprietario" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario , fk_proprietario , TB_LINK_PROPRIETARIOCARTAO.type_fk_proprietario );
		
			m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.i_unique, i_unique, TB_LINK_PROPRIETARIOCARTAO.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_fk_cartao() { return fk_cartao; } 
		public string get_fk_proprietario() { return fk_proprietario; } 
			
		public long get_int_fk_cartao() { return Convert.ToInt64 ( fk_cartao ); } 
		public long get_int_fk_proprietario() { return Convert.ToInt64 ( fk_proprietario ); } 
			
		public void set_fk_cartao ( string val ) { fk_cartao = val; m_hshChangedFields [ "fk_cartao" ]="."; } 
		public void set_fk_proprietario ( string val ) { fk_proprietario = val; m_hshChangedFields [ "fk_proprietario" ]="."; } 
		
		public void set_fk_cartao ( long val ) { fk_cartao = Convert.ToString(val); m_hshChangedFields [ "fk_cartao" ]="."; } 
		public void set_fk_proprietario ( long val ) { fk_proprietario = Convert.ToString(val); m_hshChangedFields [ "fk_proprietario" ]="."; } 
			
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_LINK_PROPRIETARIOCARTAO.i_unique );
			m_gen_dbStatement.AddSelect ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao );
			m_gen_dbStatement.AddSelect ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.i_unique, identity, TB_LINK_PROPRIETARIOCARTAO.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_LINK_ProprietarioCartao ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao, fk_cartao, TB_LINK_PROPRIETARIOCARTAO.type_fk_cartao );
			m_gen_dbStatement.AddValue ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario, fk_proprietario, TB_LINK_PROPRIETARIOCARTAO.type_fk_proprietario );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "0" )
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.i_unique, i_unique, TB_LINK_PROPRIETARIOCARTAO.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
			
		public bool select_fk_cartao ( string val_fk_cartao )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao, val_fk_cartao , TB_LINK_PROPRIETARIOCARTAO.type_fk_cartao);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_fk_proprietario ( string val_fk_proprietario )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario, val_fk_proprietario , TB_LINK_PROPRIETARIOCARTAO.type_fk_proprietario);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_fk_tudo ( string val_fk_cartao, string val_fk_proprietario )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.fk_cartao, val_fk_cartao , TB_LINK_PROPRIETARIOCARTAO.type_fk_cartao);
				m_gen_dbStatement.AddWhere ( TB_LINK_PROPRIETARIOCARTAO.fk_proprietario, val_fk_proprietario , TB_LINK_PROPRIETARIOCARTAO.type_fk_proprietario);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
		
		#if DEBUG
		
		public bool setup ( bool IsTruncate, ref string id, string var_fk_cartao, string var_fk_proprietario )
		{
			if ( IsTruncate ) 
			{
				i_unique = "";
				this.delete();
			}
		
			set_fk_cartao ( var_fk_cartao );
			set_fk_proprietario ( var_fk_proprietario );
			
			if ( create_LINK_ProprietarioCartao() == false )
			{
				return false;
			}
			
			id = get_identity();
			return true;
		}
		
		#endif
		
	}
}
