// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class T_ComoSoube : Synchronization
	{
		private string i_unique = "0";
		private string st_descricao = "";
		
		public int var_FieldCount = 2;
		
		public T_ComoSoube ()
		{
			var_Serial = TB_T_COMOSOUBE.serial;
			var_Tablename = TB_T_COMOSOUBE.Alias;
		}
		
		public T_ComoSoube ( Transaction trx )
		{
			AcquireTransaction ( ref trx );
			
			var_Serial = TB_T_COMOSOUBE.serial;
			var_Tablename = TB_T_COMOSOUBE.Alias;
			
			TraceLog ( var_Tablename + " serial : " + var_serialNumber);
		}
		
		public string exportNames()
		{
			return "st_descricao";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + st_descricao;
		}
		
		public void Reset()
		{
			i_unique = "0";
			st_descricao = "";
		
			ReleaseExclusive();
		}
		
		public void copy ( ref T_ComoSoube cpy )
		{
			st_descricao = cpy.st_descricao;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_T_COMOSOUBE.i_unique );
			st_descricao = row.GetField ( TB_T_COMOSOUBE.st_descricao );
		}
		
		public bool synchronize_T_ComoSoube ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "st_descricao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_COMOSOUBE.st_descricao , st_descricao , TB_T_COMOSOUBE.type_st_descricao );
		
			m_gen_dbStatement.AddWhere ( TB_T_COMOSOUBE.i_unique, i_unique, TB_T_COMOSOUBE.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_st_descricao() { return st_descricao; } 
			
		public void set_st_descricao ( string val ) { st_descricao = val; m_hshChangedFields [ "st_descricao" ]="."; } 
		
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_T_COMOSOUBE.i_unique );
			m_gen_dbStatement.AddSelect ( TB_T_COMOSOUBE.st_descricao );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_COMOSOUBE.i_unique, identity, TB_T_COMOSOUBE.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_T_ComoSoube ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_T_COMOSOUBE.st_descricao, st_descricao, TB_T_COMOSOUBE.type_st_descricao );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "" )
				m_gen_dbStatement.AddWhere ( TB_T_COMOSOUBE.i_unique, i_unique, TB_T_COMOSOUBE.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
		
		#if DEBUG || LOAD
		
		public bool setup ( bool IsTruncate, ref string id, string var_st_descricao )
		{
			if ( IsTruncate ) 
			{
				i_unique = "";
				this.delete();
			}
		
			set_st_descricao ( var_st_descricao );
			
			if ( create_T_ComoSoube() == false )
			{
				return false;
			}
			
			id = get_identity();
			return true;
		}
		
		#endif
		
	}
}
