// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class T_Edu_EmpresaVirtual : Synchronization
	{
		private string i_unique = "0";
		private string st_nome = "";
		private string st_codigo = "";
		private string vr_valorAcao = "0";
		
		public int var_FieldCount = 4;
		
		public T_Edu_EmpresaVirtual ( infra_Patch i_patch )  : base ( i_patch )
		{
			var_Tablename = TB_T_EDU_EMPRESAVIRTUAL.Alias;
		}
		public string exportNames()
		{
			return "st_nome,st_codigo,vr_valorAcao";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + st_nome + str_field_sep + st_codigo + str_field_sep + vr_valorAcao;
		}
		
		public void Reset()
		{
			i_unique = "0";
			st_nome = "";
			st_codigo = "";
			vr_valorAcao = "0";
		}
		
		public void copy ( ref T_Edu_EmpresaVirtual cpy )
		{
			st_nome = cpy.st_nome;
			st_codigo = cpy.st_codigo;
			vr_valorAcao = cpy.vr_valorAcao;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_T_EDU_EMPRESAVIRTUAL.i_unique );
			st_nome = row.GetField ( TB_T_EDU_EMPRESAVIRTUAL.st_nome );
			st_codigo = row.GetField ( TB_T_EDU_EMPRESAVIRTUAL.st_codigo );
			vr_valorAcao = row.GetField ( TB_T_EDU_EMPRESAVIRTUAL.vr_valorAcao );
		}
		
		public bool synchronize_T_Edu_EmpresaVirtual ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "st_nome" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EDU_EMPRESAVIRTUAL.st_nome , st_nome , TB_T_EDU_EMPRESAVIRTUAL.type_st_nome );
			if ( m_hshChangedFields [ "st_codigo" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EDU_EMPRESAVIRTUAL.st_codigo , st_codigo , TB_T_EDU_EMPRESAVIRTUAL.type_st_codigo );
			if ( m_hshChangedFields [ "vr_valorAcao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EDU_EMPRESAVIRTUAL.vr_valorAcao , vr_valorAcao , TB_T_EDU_EMPRESAVIRTUAL.type_vr_valorAcao );
		
			m_gen_dbStatement.AddWhere ( TB_T_EDU_EMPRESAVIRTUAL.i_unique, i_unique, TB_T_EDU_EMPRESAVIRTUAL.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_st_nome() { return st_nome; } 
		public string get_st_codigo() { return st_codigo; } 
		public string get_vr_valorAcao() { return vr_valorAcao; } 
			
		public long get_int_vr_valorAcao() { return Convert.ToInt64 ( vr_valorAcao ); } 
			
		public void set_st_nome ( string val ) { st_nome = val; m_hshChangedFields [ "st_nome" ]="."; } 
		public void set_st_codigo ( string val ) { st_codigo = val; m_hshChangedFields [ "st_codigo" ]="."; } 
		public void set_vr_valorAcao ( string val ) { vr_valorAcao = val; m_hshChangedFields [ "vr_valorAcao" ]="."; } 
		
		public void set_vr_valorAcao ( long val ) { vr_valorAcao = Convert.ToString(val); m_hshChangedFields [ "vr_valorAcao" ]="."; } 
			
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_T_EDU_EMPRESAVIRTUAL.i_unique );
			m_gen_dbStatement.AddSelect ( TB_T_EDU_EMPRESAVIRTUAL.st_nome );
			m_gen_dbStatement.AddSelect ( TB_T_EDU_EMPRESAVIRTUAL.st_codigo );
			m_gen_dbStatement.AddSelect ( TB_T_EDU_EMPRESAVIRTUAL.vr_valorAcao );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_EDU_EMPRESAVIRTUAL.i_unique, identity, TB_T_EDU_EMPRESAVIRTUAL.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_T_Edu_EmpresaVirtual ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_T_EDU_EMPRESAVIRTUAL.st_nome, st_nome, TB_T_EDU_EMPRESAVIRTUAL.type_st_nome );
			m_gen_dbStatement.AddValue ( TB_T_EDU_EMPRESAVIRTUAL.st_codigo, st_codigo, TB_T_EDU_EMPRESAVIRTUAL.type_st_codigo );
			m_gen_dbStatement.AddValue ( TB_T_EDU_EMPRESAVIRTUAL.vr_valorAcao, vr_valorAcao, TB_T_EDU_EMPRESAVIRTUAL.type_vr_valorAcao );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "0" )
				m_gen_dbStatement.AddWhere ( TB_T_EDU_EMPRESAVIRTUAL.i_unique, i_unique, TB_T_EDU_EMPRESAVIRTUAL.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
			
		public bool select_rows_codigo ( string val_st_codigo )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_EDU_EMPRESAVIRTUAL.st_codigo, val_st_codigo , TB_T_EDU_EMPRESAVIRTUAL.type_st_codigo);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
	}
}
