// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class T_ExtraGift : Synchronization
	{
		private string i_unique = "0";
		private string st_nome = "";
		private string vr_valor = "0";
		private string fk_empresa = "0";
		
		public int var_FieldCount = 4;
		
		public T_ExtraGift ( infra_Patch i_patch )  : base ( i_patch )
		{
			var_Tablename = TB_T_EXTRAGIFT.Alias;
		}
		public string exportNames()
		{
			return "st_nome,vr_valor,fk_empresa";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + st_nome + str_field_sep + vr_valor + str_field_sep + fk_empresa;
		}
		
		public void Reset()
		{
			i_unique = "0";
			st_nome = "";
			vr_valor = "0";
			fk_empresa = "0";
		}
		
		public void copy ( ref T_ExtraGift cpy )
		{
			st_nome = cpy.st_nome;
			vr_valor = cpy.vr_valor;
			fk_empresa = cpy.fk_empresa;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_T_EXTRAGIFT.i_unique );
			st_nome = row.GetField ( TB_T_EXTRAGIFT.st_nome );
			vr_valor = row.GetField ( TB_T_EXTRAGIFT.vr_valor );
			fk_empresa = row.GetField ( TB_T_EXTRAGIFT.fk_empresa );
		}
		
		public bool synchronize_T_ExtraGift ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "st_nome" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EXTRAGIFT.st_nome , st_nome , TB_T_EXTRAGIFT.type_st_nome );
			if ( m_hshChangedFields [ "vr_valor" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EXTRAGIFT.vr_valor , vr_valor , TB_T_EXTRAGIFT.type_vr_valor );
			if ( m_hshChangedFields [ "fk_empresa" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_EXTRAGIFT.fk_empresa , fk_empresa , TB_T_EXTRAGIFT.type_fk_empresa );
		
			m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.i_unique, i_unique, TB_T_EXTRAGIFT.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_st_nome() { return st_nome; } 
		public string get_vr_valor() { return vr_valor; } 
		public string get_fk_empresa() { return fk_empresa; } 
			
		public long get_int_vr_valor() { return Convert.ToInt64 ( vr_valor ); } 
		public long get_int_fk_empresa() { return Convert.ToInt64 ( fk_empresa ); } 
			
		public void set_st_nome ( string val ) { st_nome = val; m_hshChangedFields [ "st_nome" ]="."; } 
		public void set_vr_valor ( string val ) { vr_valor = val; m_hshChangedFields [ "vr_valor" ]="."; } 
		public void set_fk_empresa ( string val ) { fk_empresa = val; m_hshChangedFields [ "fk_empresa" ]="."; } 
		
		public void set_vr_valor ( long val ) { vr_valor = Convert.ToString(val); m_hshChangedFields [ "vr_valor" ]="."; } 
		public void set_fk_empresa ( long val ) { fk_empresa = Convert.ToString(val); m_hshChangedFields [ "fk_empresa" ]="."; } 
			
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_T_EXTRAGIFT.i_unique );
			m_gen_dbStatement.AddSelect ( TB_T_EXTRAGIFT.st_nome );
			m_gen_dbStatement.AddSelect ( TB_T_EXTRAGIFT.vr_valor );
			m_gen_dbStatement.AddSelect ( TB_T_EXTRAGIFT.fk_empresa );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.i_unique, identity, TB_T_EXTRAGIFT.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_T_ExtraGift ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_T_EXTRAGIFT.st_nome, st_nome, TB_T_EXTRAGIFT.type_st_nome );
			m_gen_dbStatement.AddValue ( TB_T_EXTRAGIFT.vr_valor, vr_valor, TB_T_EXTRAGIFT.type_vr_valor );
			m_gen_dbStatement.AddValue ( TB_T_EXTRAGIFT.fk_empresa, fk_empresa, TB_T_EXTRAGIFT.type_fk_empresa );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "0" )
				m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.i_unique, i_unique, TB_T_EXTRAGIFT.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
			
		public bool select_fk_emp ( string val_fk_empresa )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.fk_empresa, val_fk_empresa , TB_T_EXTRAGIFT.type_fk_empresa);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_rows_nome_emp ( string val_st_nome, string val_fk_empresa )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.st_nome, val_st_nome , TB_T_EXTRAGIFT.type_st_nome);
				m_gen_dbStatement.AddWhere ( TB_T_EXTRAGIFT.fk_empresa, val_fk_empresa , TB_T_EXTRAGIFT.type_fk_empresa);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
	}
}
