// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class T_PendPayFone : Synchronization
	{
		private string i_unique = "0";
		private string fk_cartao = "0";
		private string fk_terminal = "0";
		private string nu_nsu = "0";
		private string vr_valor = "0";
		private string dt_inclusao = "1900-01-01 00:00:00";
		private string en_situacao = "";
		private string fk_empresa = "0";
		private string fk_loja = "0";
		
		public int var_FieldCount = 9;
		
		public T_PendPayFone ( infra_Patch i_patch )  : base ( i_patch )
		{
			var_Tablename = TB_T_PENDPAYFONE.Alias;
		}
		public string exportNames()
		{
			return "fk_cartao,fk_terminal,nu_nsu,vr_valor,dt_inclusao,en_situacao,fk_empresa,fk_loja";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + fk_cartao + str_field_sep + fk_terminal + str_field_sep + nu_nsu + str_field_sep + vr_valor + str_field_sep + dt_inclusao + str_field_sep + en_situacao + str_field_sep + fk_empresa + str_field_sep + fk_loja;
		}
		
		public void Reset()
		{
			i_unique = "0";
			fk_cartao = "0";
			fk_terminal = "0";
			nu_nsu = "0";
			vr_valor = "0";
			dt_inclusao = "1900-01-01 00:00:00";
			en_situacao = "";
			fk_empresa = "0";
			fk_loja = "0";
		}
		
		public void copy ( ref T_PendPayFone cpy )
		{
			fk_cartao = cpy.fk_cartao;
			fk_terminal = cpy.fk_terminal;
			nu_nsu = cpy.nu_nsu;
			vr_valor = cpy.vr_valor;
			dt_inclusao = cpy.dt_inclusao;
			en_situacao = cpy.en_situacao;
			fk_empresa = cpy.fk_empresa;
			fk_loja = cpy.fk_loja;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_T_PENDPAYFONE.i_unique );
			fk_cartao = row.GetField ( TB_T_PENDPAYFONE.fk_cartao );
			fk_terminal = row.GetField ( TB_T_PENDPAYFONE.fk_terminal );
			nu_nsu = row.GetField ( TB_T_PENDPAYFONE.nu_nsu );
			vr_valor = row.GetField ( TB_T_PENDPAYFONE.vr_valor );
			dt_inclusao = ConvertTime ( row.GetField ( TB_T_PENDPAYFONE.dt_inclusao ) );
			en_situacao = row.GetField ( TB_T_PENDPAYFONE.en_situacao );
			fk_empresa = row.GetField ( TB_T_PENDPAYFONE.fk_empresa );
			fk_loja = row.GetField ( TB_T_PENDPAYFONE.fk_loja );
		}
		
		public bool synchronize_T_PendPayFone ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "fk_cartao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.fk_cartao , fk_cartao , TB_T_PENDPAYFONE.type_fk_cartao );
			if ( m_hshChangedFields [ "fk_terminal" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.fk_terminal , fk_terminal , TB_T_PENDPAYFONE.type_fk_terminal );
			if ( m_hshChangedFields [ "nu_nsu" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.nu_nsu , nu_nsu , TB_T_PENDPAYFONE.type_nu_nsu );
			if ( m_hshChangedFields [ "vr_valor" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.vr_valor , vr_valor , TB_T_PENDPAYFONE.type_vr_valor );
			if ( m_hshChangedFields [ "dt_inclusao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.dt_inclusao , dt_inclusao , TB_T_PENDPAYFONE.type_dt_inclusao );
			if ( m_hshChangedFields [ "en_situacao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.en_situacao , en_situacao , TB_T_PENDPAYFONE.type_en_situacao );
			if ( m_hshChangedFields [ "fk_empresa" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.fk_empresa , fk_empresa , TB_T_PENDPAYFONE.type_fk_empresa );
			if ( m_hshChangedFields [ "fk_loja" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PENDPAYFONE.fk_loja , fk_loja , TB_T_PENDPAYFONE.type_fk_loja );
		
			m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.i_unique, i_unique, TB_T_PENDPAYFONE.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_fk_cartao() { return fk_cartao; } 
		public string get_fk_terminal() { return fk_terminal; } 
		public string get_nu_nsu() { return nu_nsu; } 
		public string get_vr_valor() { return vr_valor; } 
		public string get_dt_inclusao() { return dt_inclusao; } 
		public string get_en_situacao() { return en_situacao; } 
		public string get_fk_empresa() { return fk_empresa; } 
		public string get_fk_loja() { return fk_loja; } 
			
		public long get_int_fk_cartao() { return Convert.ToInt64 ( fk_cartao ); } 
		public long get_int_fk_terminal() { return Convert.ToInt64 ( fk_terminal ); } 
		public long get_int_nu_nsu() { return Convert.ToInt64 ( nu_nsu ); } 
		public long get_int_vr_valor() { return Convert.ToInt64 ( vr_valor ); } 
		public long get_int_fk_empresa() { return Convert.ToInt64 ( fk_empresa ); } 
		public long get_int_fk_loja() { return Convert.ToInt64 ( fk_loja ); } 
			
		public void set_fk_cartao ( string val ) { fk_cartao = val; m_hshChangedFields [ "fk_cartao" ]="."; } 
		public void set_fk_terminal ( string val ) { fk_terminal = val; m_hshChangedFields [ "fk_terminal" ]="."; } 
		public void set_nu_nsu ( string val ) { nu_nsu = val; m_hshChangedFields [ "nu_nsu" ]="."; } 
		public void set_vr_valor ( string val ) { vr_valor = val; m_hshChangedFields [ "vr_valor" ]="."; } 
		public void set_dt_inclusao ( string val ) { dt_inclusao = val; m_hshChangedFields [ "dt_inclusao" ]="."; } 
		public void set_en_situacao ( string val ) { en_situacao = val; m_hshChangedFields [ "en_situacao" ]="."; } 
		public void set_fk_empresa ( string val ) { fk_empresa = val; m_hshChangedFields [ "fk_empresa" ]="."; } 
		public void set_fk_loja ( string val ) { fk_loja = val; m_hshChangedFields [ "fk_loja" ]="."; } 
		
		public void set_fk_cartao ( long val ) { fk_cartao = Convert.ToString(val); m_hshChangedFields [ "fk_cartao" ]="."; } 
		public void set_fk_terminal ( long val ) { fk_terminal = Convert.ToString(val); m_hshChangedFields [ "fk_terminal" ]="."; } 
		public void set_nu_nsu ( long val ) { nu_nsu = Convert.ToString(val); m_hshChangedFields [ "nu_nsu" ]="."; } 
		public void set_vr_valor ( long val ) { vr_valor = Convert.ToString(val); m_hshChangedFields [ "vr_valor" ]="."; } 
		public void set_fk_empresa ( long val ) { fk_empresa = Convert.ToString(val); m_hshChangedFields [ "fk_empresa" ]="."; } 
		public void set_fk_loja ( long val ) { fk_loja = Convert.ToString(val); m_hshChangedFields [ "fk_loja" ]="."; } 
			
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.i_unique );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.fk_cartao );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.fk_terminal );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.nu_nsu );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.vr_valor );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.dt_inclusao );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.en_situacao );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.fk_empresa );
			m_gen_dbStatement.AddSelect ( TB_T_PENDPAYFONE.fk_loja );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.i_unique, identity, TB_T_PENDPAYFONE.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_T_PendPayFone ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.fk_cartao, fk_cartao, TB_T_PENDPAYFONE.type_fk_cartao );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.fk_terminal, fk_terminal, TB_T_PENDPAYFONE.type_fk_terminal );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.nu_nsu, nu_nsu, TB_T_PENDPAYFONE.type_nu_nsu );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.vr_valor, vr_valor, TB_T_PENDPAYFONE.type_vr_valor );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.dt_inclusao, dt_inclusao, TB_T_PENDPAYFONE.type_dt_inclusao );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.en_situacao, en_situacao, TB_T_PENDPAYFONE.type_en_situacao );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.fk_empresa, fk_empresa, TB_T_PENDPAYFONE.type_fk_empresa );
			m_gen_dbStatement.AddValue ( TB_T_PENDPAYFONE.fk_loja, fk_loja, TB_T_PENDPAYFONE.type_fk_loja );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "0" )
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.i_unique, i_unique, TB_T_PENDPAYFONE.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
			
		public bool select_rows_cart_sit ( string val_fk_cartao, string val_en_situacao )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.fk_cartao, val_fk_cartao , TB_T_PENDPAYFONE.type_fk_cartao);
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.en_situacao, val_en_situacao , TB_T_PENDPAYFONE.type_en_situacao);
			
				m_gen_dbStatement.AddOrderBy ( TB_T_PENDPAYFONE.dt_inclusao );
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_rows_nsu ( string val_nu_nsu )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.nu_nsu, val_nu_nsu , TB_T_PENDPAYFONE.type_nu_nsu);
			
				m_gen_dbStatement.AddOrderBy ( TB_T_PENDPAYFONE.dt_inclusao );
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_rows_data ( string val_dt_inclusao, string val_dt_inclusao1, string val_en_situacao )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhereGreaterEqual ( TB_T_PENDPAYFONE.dt_inclusao, val_dt_inclusao , TB_T_PENDPAYFONE.type_dt_inclusao);
				m_gen_dbStatement.AddWhereLessThan ( TB_T_PENDPAYFONE.dt_inclusao, val_dt_inclusao1 , TB_T_PENDPAYFONE.type_dt_inclusao);
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.en_situacao, val_en_situacao , TB_T_PENDPAYFONE.type_en_situacao);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_rows_data_empresa ( string val_dt_inclusao, string val_dt_inclusao1, string val_en_situacao, string val_fk_empresa )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhereGreaterEqual ( TB_T_PENDPAYFONE.dt_inclusao, val_dt_inclusao , TB_T_PENDPAYFONE.type_dt_inclusao);
				m_gen_dbStatement.AddWhereLessThan ( TB_T_PENDPAYFONE.dt_inclusao, val_dt_inclusao1 , TB_T_PENDPAYFONE.type_dt_inclusao);
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.en_situacao, val_en_situacao , TB_T_PENDPAYFONE.type_en_situacao);
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.fk_empresa, val_fk_empresa , TB_T_PENDPAYFONE.type_fk_empresa);
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
			
		public bool select_rows_cart_term ( string val_fk_cartao, string val_fk_terminal )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.fk_cartao, val_fk_cartao , TB_T_PENDPAYFONE.type_fk_cartao);
				m_gen_dbStatement.AddWhere ( TB_T_PENDPAYFONE.fk_terminal, val_fk_terminal , TB_T_PENDPAYFONE.type_fk_terminal);
			
				m_gen_dbStatement.AddOrderBy ( TB_T_PENDPAYFONE.dt_inclusao );
			
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return HasRows();
		}
	}
}
