// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;

namespace SyCrafEngine
{
	public class T_Profissoes : Synchronization
	{
		private string i_unique = "0";
		private string st_codigo = "";
		private string st_profissao = "";
		
		public int var_FieldCount = 3;
		
		public T_Profissoes ( infra_Patch i_patch )  : base ( i_patch )
		{
			var_Tablename = TB_T_PROFISSOES.Alias;
		}
		public string exportNames()
		{
			return "st_codigo,st_profissao";
		}
		
		public string exportCSV()
		{
			return i_unique + str_field_sep + st_codigo + str_field_sep + st_profissao;
		}
		
		public void Reset()
		{
			i_unique = "0";
			st_codigo = "";
			st_profissao = "";
		}
		
		public void copy ( ref T_Profissoes cpy )
		{
			st_codigo = cpy.st_codigo;
			st_profissao = cpy.st_profissao;
		}
		
		public override void fetchRetrieve ( ref DB_Row row )
		{
			i_unique = row.GetField ( TB_T_PROFISSOES.i_unique );
			st_codigo = row.GetField ( TB_T_PROFISSOES.st_codigo );
			st_profissao = row.GetField ( TB_T_PROFISSOES.st_profissao );
		}
		
		public bool synchronize_T_Profissoes ( )
		{
			try{
			
			if ( m_hshChangedFields.Count == 0 )
				return true;
			
			StartUpdate();
		
			if ( m_hshChangedFields [ "st_codigo" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PROFISSOES.st_codigo , st_codigo , TB_T_PROFISSOES.type_st_codigo );
			if ( m_hshChangedFields [ "st_profissao" ] != null )
				m_gen_dbStatement.AddUpdate ( TB_T_PROFISSOES.st_profissao , st_profissao , TB_T_PROFISSOES.type_st_profissao );
		
			m_gen_dbStatement.AddWhere ( TB_T_PROFISSOES.i_unique, i_unique, TB_T_PROFISSOES.type_i_unique );
		
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
		
			return Update();
		}
			
		public string get_identity() { return i_unique; } 
		public string get_st_codigo() { return st_codigo; } 
		public string get_st_profissao() { return st_profissao; } 
			
		public void set_st_codigo ( string val ) { st_codigo = val; m_hshChangedFields [ "st_codigo" ]="."; } 
		public void set_st_profissao ( string val ) { st_profissao = val; m_hshChangedFields [ "st_profissao" ]="."; } 
		
		public void fieldSelection()
		{
			m_gen_dbStatement.AddSelect ( TB_T_PROFISSOES.i_unique );
			m_gen_dbStatement.AddSelect ( TB_T_PROFISSOES.st_codigo );
			m_gen_dbStatement.AddSelect ( TB_T_PROFISSOES.st_profissao );
		}
			
		public bool selectAll()
		{
			do
			{
				StartSelect();
				fieldSelection();
				
				if ( !executeQuery() )
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			return  HasRows();
		}
		
		public bool selectIdentity ( string identity )
		{
			do
			{
				StartSelect();
				fieldSelection();
			
				m_gen_dbStatement.AddWhere ( TB_T_PROFISSOES.i_unique, identity, TB_T_PROFISSOES.type_i_unique );
			
				if ( !executeQuery())
					return false;
			}
			while ( EndSelect() == false ); // row lock
			
			if ( HasRows() == true)
			{
				DB_Row row = m_db_result.GetFirstRow();
				fetchRetrieve ( ref row );
				return true;
			}
			
			return false;
		}
		
		public bool create_T_Profissoes ( )
		{
			try{
			string new_id = "";
			
			StartInsert();
			
			m_gen_dbStatement.AddValue ( TB_T_PROFISSOES.st_codigo, st_codigo, TB_T_PROFISSOES.type_st_codigo );
			m_gen_dbStatement.AddValue ( TB_T_PROFISSOES.st_profissao, st_profissao, TB_T_PROFISSOES.type_st_profissao );
			
			if ( !ExecuteScalar ( ref new_id ) )
				return false;
			
			i_unique = new_id;
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return true;
		}
			
		public bool delete ( )
		{
		
			bool ret = false;
		
			try{
			StartDelete();
			
			if ( i_unique != "" )
				m_gen_dbStatement.AddWhere ( TB_T_PROFISSOES.i_unique, i_unique, TB_T_PROFISSOES.type_i_unique );
			
			ret = Execute();
			
			} catch ( System.Exception ex ) {
				StreamWriter wr = new StreamWriter ( 	"CRITICAL_" + var_Tablename + "_" + "_" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Day.ToString().PadLeft ( 2, '0' ) + "_" + DateTime.Now.Hour.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Minute.ToString().PadLeft ( 2, '0' ) + DateTime.Now.Second.ToString().PadLeft ( 2, '0' ) + ".txt" );
				wr.WriteLine ( ex.ToString() );
				wr.Flush();
				wr.Close();
			}
			
			return ret; 
		}
	}
}
