// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosCartao : DataPortable 
	{
		public const string st_cpf = "st_cpf";
		public const string st_empresa = "st_empresa";
		public const string st_matricula = "st_matricula";
		public const string st_titularidade = "st_titularidade";
		public const string st_senha = "st_senha";
		public const string tg_tipoCartao = "tg_tipoCartao";
		public const string vr_limiteTotal = "vr_limiteTotal";
		public const string vr_limiteMensal = "vr_limiteMensal";
		public const string vr_limiteRotativo = "vr_limiteRotativo";
		public const string vr_extraCota = "vr_extraCota";
		public const string st_banco = "st_banco";
		public const string st_agencia = "st_agencia";
		public const string st_conta = "st_conta";
		public const string st_celCartao = "st_celCartao";
		public const string tg_gerencial = "tg_gerencial";
		public const string st_vencimento = "st_vencimento";
		public const string tg_status = "tg_status";
		public const string st_proprietario = "st_proprietario";
		public const string vr_dispMes = "vr_dispMes";
		public const string vr_dispTotal = "vr_dispTotal";
		public const string dt_ultUso = "dt_ultUso";
		public const string dt_ultCarga = "dt_ultCarga";
		
		public DadosCartao() { }
		
		public void Clear()
		{
			set_st_cpf ( "" );
			set_st_empresa ( "" );
			set_st_matricula ( "" );
			set_st_titularidade ( "" );
			set_st_senha ( "" );
			set_tg_tipoCartao ( "" );
			set_vr_limiteTotal ( "" );
			set_vr_limiteMensal ( "" );
			set_vr_limiteRotativo ( "" );
			set_vr_extraCota ( "" );
			set_st_banco ( "" );
			set_st_agencia ( "" );
			set_st_conta ( "" );
			set_st_celCartao ( "" );
			set_tg_gerencial ( "" );
			set_st_vencimento ( "" );
			set_tg_status ( "" );
			set_st_proprietario ( "" );
			set_vr_dispMes ( "" );
			set_vr_dispTotal ( "" );
			set_dt_ultUso ( "" );
			set_dt_ultCarga ( "" );
		}
		
		public DadosCartao ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_cpf ( port.getValue ( st_cpf ) );
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_st_matricula ( port.getValue ( st_matricula ) );
			set_st_titularidade ( port.getValue ( st_titularidade ) );
			set_st_senha ( port.getValue ( st_senha ) );
			set_tg_tipoCartao ( port.getValue ( tg_tipoCartao ) );
			set_vr_limiteTotal ( port.getValue ( vr_limiteTotal ) );
			set_vr_limiteMensal ( port.getValue ( vr_limiteMensal ) );
			set_vr_limiteRotativo ( port.getValue ( vr_limiteRotativo ) );
			set_vr_extraCota ( port.getValue ( vr_extraCota ) );
			set_st_banco ( port.getValue ( st_banco ) );
			set_st_agencia ( port.getValue ( st_agencia ) );
			set_st_conta ( port.getValue ( st_conta ) );
			set_st_celCartao ( port.getValue ( st_celCartao ) );
			set_tg_gerencial ( port.getValue ( tg_gerencial ) );
			set_st_vencimento ( port.getValue ( st_vencimento ) );
			set_tg_status ( port.getValue ( tg_status ) );
			set_st_proprietario ( port.getValue ( st_proprietario ) );
			set_vr_dispMes ( port.getValue ( vr_dispMes ) );
			set_vr_dispTotal ( port.getValue ( vr_dispTotal ) );
			set_dt_ultUso ( port.getValue ( dt_ultUso ) );
			set_dt_ultCarga ( port.getValue ( dt_ultCarga ) );
		}
		
		public string get_st_cpf () { return getValue ( st_cpf ); }
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_st_matricula () { return getValue ( st_matricula ); }
		public string get_st_titularidade () { return getValue ( st_titularidade ); }
		public string get_st_senha () { return getValue ( st_senha ); }
		public string get_tg_tipoCartao () { return getValue ( tg_tipoCartao ); }
		public string get_vr_limiteTotal () { return getValue ( vr_limiteTotal ); }
		public string get_vr_limiteMensal () { return getValue ( vr_limiteMensal ); }
		public string get_vr_limiteRotativo () { return getValue ( vr_limiteRotativo ); }
		public string get_vr_extraCota () { return getValue ( vr_extraCota ); }
		public string get_st_banco () { return getValue ( st_banco ); }
		public string get_st_agencia () { return getValue ( st_agencia ); }
		public string get_st_conta () { return getValue ( st_conta ); }
		public string get_st_celCartao () { return getValue ( st_celCartao ); }
		public string get_tg_gerencial () { return getValue ( tg_gerencial ); }
		public string get_st_vencimento () { return getValue ( st_vencimento ); }
		public string get_tg_status () { return getValue ( tg_status ); }
		public string get_st_proprietario () { return getValue ( st_proprietario ); }
		public string get_vr_dispMes () { return getValue ( vr_dispMes ); }
		public string get_vr_dispTotal () { return getValue ( vr_dispTotal ); }
		public string get_dt_ultUso () { return getValue ( dt_ultUso ); }
		public string get_dt_ultCarga () { return getValue ( dt_ultCarga ); }
		
		public void set_st_cpf ( string val ) { setValue ( st_cpf , val ); }
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_st_matricula ( string val ) { setValue ( st_matricula , val ); }
		public void set_st_titularidade ( string val ) { setValue ( st_titularidade , val ); }
		public void set_st_senha ( string val ) { setValue ( st_senha , val ); }
		public void set_tg_tipoCartao ( string val ) { setValue ( tg_tipoCartao , val ); }
		public void set_vr_limiteTotal ( string val ) { setValue ( vr_limiteTotal , val ); }
		public void set_vr_limiteMensal ( string val ) { setValue ( vr_limiteMensal , val ); }
		public void set_vr_limiteRotativo ( string val ) { setValue ( vr_limiteRotativo , val ); }
		public void set_vr_extraCota ( string val ) { setValue ( vr_extraCota , val ); }
		public void set_st_banco ( string val ) { setValue ( st_banco , val ); }
		public void set_st_agencia ( string val ) { setValue ( st_agencia , val ); }
		public void set_st_conta ( string val ) { setValue ( st_conta , val ); }
		public void set_st_celCartao ( string val ) { setValue ( st_celCartao , val ); }
		public void set_tg_gerencial ( string val ) { setValue ( tg_gerencial , val ); }
		public void set_st_vencimento ( string val ) { setValue ( st_vencimento , val ); }
		public void set_tg_status ( string val ) { setValue ( tg_status , val ); }
		public void set_st_proprietario ( string val ) { setValue ( st_proprietario , val ); }
		public void set_vr_dispMes ( string val ) { setValue ( vr_dispMes , val ); }
		public void set_vr_dispTotal ( string val ) { setValue ( vr_dispTotal , val ); }
		public void set_dt_ultUso ( string val ) { setValue ( dt_ultUso , val ); }
		public void set_dt_ultCarga ( string val ) { setValue ( dt_ultCarga , val ); }
	}
}
