// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.IO;
using System.Threading;
using System.Collections;
using System.Windows.Forms;
using SyCrafEngine;

namespace Client
{
	#if ROBOT
	
	public class SimulationLayer
	{
		public void type_base ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_cartaoProprietario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_proprietario ( ref Communication var_Comm, bool ret , DadosProprietario output_cont_dp )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_PROPRIETARIO.dp , output_cont_dp as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_login ( ref Communication var_Comm, bool ret , string output_tg_trocaSenha, CNetHeader output_cont_header )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_LOGIN.tg_trocaSenha, output_tg_trocaSenha ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_EXEC_LOGIN.header , output_cont_header as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_logoff ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_trocaSenha ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_usuario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_listaUsuarios ( ref Communication var_Comm, bool ret , string output_st_csv_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_LISTAUSUARIOS.st_csv_id, output_st_csv_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_usuarios ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_usuarios )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_usuarios = new DataPortable();
		
			dp_array_generic_usuarios.MapTagArray ( COMM_OUT_FETCH_USUARIOS.usuarios , ref output_array_generic_usuarios );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_usuarios );
		}
			
		public void exec_alteraUsuario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_empresa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_loja ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_dadosEmpresa ( ref Communication var_Comm, bool ret , DadosEmpresa output_cont_de )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_DADOSEMPRESA.de , output_cont_de as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void fetch_dadosLoja ( ref Communication var_Comm, bool ret , DadosLoja output_cont_dl )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_DADOSLOJA.dl , output_cont_dl as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_alteraEmpresa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_alteraLoja ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_codTerminal ( ref Communication var_Comm, bool ret , string output_st_terminal )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CODTERMINAL.st_terminal, output_st_terminal ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_nomeEmpresa ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_NOMEEMPRESA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_validaEmpresa ( ref Communication var_Comm, bool ret , string output_st_nome )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_VALIDAEMPRESA.st_nome, output_st_nome ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void ins_terminal ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_terminais ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_TERMINAIS.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_terminalLoja ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_TERMINALLOJA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void del_Terminal ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_consultaLoja ( ref Communication var_Comm, bool ret , string output_st_csv_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTALOJA.st_csv_id, output_st_csv_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_consultaEmpresa ( ref Communication var_Comm, bool ret , string output_st_csv_empresas )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTAEMPRESA.st_csv_empresas, output_st_csv_empresas ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_consultaAuditoria ( ref Communication var_Comm, bool ret , string output_st_csv_audit )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTAAUDITORIA.st_csv_audit, output_st_csv_audit ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_alteraTerminal ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_limitesCartao ( ref Communication var_Comm, bool ret , string output_st_csv_cartoes )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_LIMITESCARTAO.st_csv_cartoes, output_st_csv_cartoes ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_alteraCartao ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_consultaCartao ( ref Communication var_Comm, bool ret , string output_st_csv_cartao )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTACARTAO.st_csv_cartao, output_st_csv_cartao ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void infra_SchedulerDispatcher ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void schedule_base ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_pos_vendaEmpresarial ( ref Communication var_Comm, bool ret , string output_st_msg, POS_Resposta output_cont_pr )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_POS_VENDAEMPRESARIAL.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_EXEC_POS_VENDAEMPRESARIAL.pr , output_cont_pr as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_pos_confirmaVendaEmpresarial ( ref Communication var_Comm, bool ret , string output_st_msg, POS_Resposta output_cont_pr )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_POS_CONFIRMAVENDAEMPRESARIAL.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_EXEC_POS_CONFIRMAVENDAEMPRESARIAL.pr , output_cont_pr as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void fetch_consultaTransacao ( ref Communication var_Comm, bool ret , string output_st_csv_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTATRANSACAO.st_csv_id, output_st_csv_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_gravaPendencia ( ref Communication var_Comm, bool ret , string output_st_nsu, string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_GRAVAPENDENCIA.st_nsu, output_st_nsu ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_GRAVAPENDENCIA.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_GRAVAPENDENCIA.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_consultaPendencia ( ref Communication var_Comm, bool ret , string output_st_nsu, string output_st_valor, string output_st_nomeLoja, string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAPENDENCIA.st_nsu, output_st_nsu ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAPENDENCIA.st_valor, output_st_valor ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAPENDENCIA.st_nomeLoja, output_st_nomeLoja ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAPENDENCIA.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAPENDENCIA.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void type_pf_base ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_TYPE_PF_BASE.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_TYPE_PF_BASE.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_cancelaPendencia ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAPENDENCIA.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAPENDENCIA.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_autorizaVendaPendente ( ref Communication var_Comm, bool ret , string output_st_nsu_autorizado, string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAVENDAPENDENTE.st_nsu_autorizado, output_st_nsu_autorizado ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAVENDAPENDENTE.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAVENDAPENDENTE.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_consultaAutorizacao ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAAUTORIZACAO.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CONSULTAAUTORIZACAO.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_EXEC_PF_CONSULTAAUTORIZACAO.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void ins_payFone ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_payFoneLojista ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_alteraSenhaCartao ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_pf_cancelaVenda ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAVENDA.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAVENDA.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_pf_telefoneLojista ( ref Communication var_Comm, bool ret , string output_st_telefone )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_PF_TELEFONELOJISTA.st_telefone, output_st_telefone ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_dadosCartao ( ref Communication var_Comm, bool ret , string output_nu_maxParcelas, string output_vr_dispMes, string output_vr_dispTotal, string output_st_nome )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSCARTAO.nu_maxParcelas, output_nu_maxParcelas ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSCARTAO.vr_dispMes, output_vr_dispMes ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSCARTAO.vr_dispTotal, output_vr_dispTotal ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSCARTAO.st_nome, output_st_nome ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_nomeLoja ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_NOMELOJA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_termLoja ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_TERMLOJA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_nomeLojaTerminal ( ref Communication var_Comm, bool ret , string output_st_nome_loja )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_NOMELOJATERMINAL.st_nome_loja, output_st_nome_loja ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_cancelaPendenciaLojista ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAPENDENCIALOJISTA.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_CANCELAPENDENCIALOJISTA.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_dadosNSU ( ref Communication var_Comm, bool ret , DadosNSU output_cont_d_nsu )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_DADOSNSU.d_nsu , output_cont_d_nsu as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_pos_cancelaVendaEmpresarial ( ref Communication var_Comm, bool ret , string output_st_msg, POS_Resposta output_cont_pr )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_POS_CANCELAVENDAEMPRESARIAL.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_EXEC_POS_CANCELAVENDAEMPRESARIAL.pr , output_cont_pr as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void fetch_rel_1_rtc ( ref Communication var_Comm, bool ret , string output_st_csv, string output_st_empresa, string output_st_total_periodo, string output_st_cartao, string output_st_total_cancelado, string output_st_parcs, string output_st_parcs_total, string output_st_parcs_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_empresa, output_st_empresa ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_total_periodo, output_st_total_periodo ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_cartao, output_st_cartao ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_total_cancelado, output_st_total_cancelado ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_parcs, output_st_parcs ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_parcs_total, output_st_parcs_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_1_RTC.st_parcs_content, output_st_parcs_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_rel_2_rlt ( ref Communication var_Comm, bool ret , string output_st_total, string output_st_total_cancelado, string output_st_csv_subtotal, string output_st_csv_subtotal_cancelado, string output_st_csv, string output_st_nome_loja, ArrayList output_array_generic_lstTerminais )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_total, output_st_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_total_cancelado, output_st_total_cancelado ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_csv_subtotal, output_st_csv_subtotal ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_csv_subtotal_cancelado, output_st_csv_subtotal_cancelado ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_2_RLT.st_nome_loja, output_st_nome_loja ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lstTerminais = new DataPortable();
		
			dp_array_generic_lstTerminais.MapTagArray ( COMM_OUT_FETCH_REL_2_RLT.lstTerminais , ref output_array_generic_lstTerminais );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstTerminais );
		}
			
		public void schedule_nsu ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_pf_autorizaInstalacao ( ref Communication var_Comm, bool ret , string output_st_codResp, string output_st_msg, string output_st_telefone, string output_st_terminal, string output_tg_tipoCelular, string output_st_lojaTB )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.st_codResp, output_st_codResp ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.st_msg, output_st_msg ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.st_telefone, output_st_telefone ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.st_terminal, output_st_terminal ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.tg_tipoCelular, output_tg_tipoCelular ); 
			dp_out.MapTagValue ( COMM_OUT_EXEC_PF_AUTORIZAINSTALACAO.st_lojaTB, output_st_lojaTB ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void ins_agenda ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void schedule_fech_mensal ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_agenda ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_AGENDA.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void del_agenda ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_rel_3_fech ( ref Communication var_Comm, bool ret , string output_st_empresa, string output_st_csv_cartao, string output_st_csv_loja, string output_st_csv_loja_content, string output_st_csv_subtotal_loja, string output_st_csv_subtotal_cartao, string output_st_csv_cartao_content, string output_st_total )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_empresa, output_st_empresa ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_cartao, output_st_csv_cartao ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_loja, output_st_csv_loja ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_loja_content, output_st_csv_loja_content ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_subtotal_loja, output_st_csv_subtotal_loja ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_subtotal_cartao, output_st_csv_subtotal_cartao ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_csv_cartao_content, output_st_csv_cartao_content ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_3_FECH.st_total, output_st_total ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_memory ( ref Communication var_Comm, bool ret , string output_st_new_block, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_MEMORY.st_new_block, output_st_new_block ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_MEMORY.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void schedule_educacional ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_listaConveniosLoja ( ref Communication var_Comm, bool ret , string output_st_cnpj, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_LISTACONVENIOSLOJA.st_cnpj, output_st_cnpj ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_LISTACONVENIOSLOJA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_rel_4_rrp ( ref Communication var_Comm, bool ret , string output_st_csv_content, string output_st_nome_empresa, string output_st_csv_lojas, string output_st_csv_subtotal, string output_st_total, string output_st_csv_nome_lojas, string output_st_csv_subtotal_geral, string output_st_total_geral )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_csv_content, output_st_csv_content ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_nome_empresa, output_st_nome_empresa ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_csv_lojas, output_st_csv_lojas ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_csv_subtotal, output_st_csv_subtotal ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_total, output_st_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_csv_nome_lojas, output_st_csv_nome_lojas ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_csv_subtotal_geral, output_st_csv_subtotal_geral ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_4_RRP.st_total_geral, output_st_total_geral ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_dadosAluno ( ref Communication var_Comm, bool ret , DadosCartaoEdu output_cont_dce )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_DADOSALUNO.dce , output_cont_dce as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void exec_depotEduImediato ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_rel_edu_extrato ( ref Communication var_Comm, bool ret , string output_st_csv, string output_st_empresa, string output_st_total_periodo )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_EDU_EXTRATO.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_EDU_EXTRATO.st_empresa, output_st_empresa ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_EDU_EXTRATO.st_total_periodo, output_st_total_periodo ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_bloqueio ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_desbloqueio ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_cancelaEmpresa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_fetch_saldo_edu ( ref Communication var_Comm, bool ret , DadosCartaoEdu output_cont_dce )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_WEB_FETCH_SALDO_EDU.dce , output_cont_dce as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void web_fetch_edu_inicial ( ref Communication var_Comm, bool ret , string output_tg_resp )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_EDU_INICIAL.tg_resp, output_tg_resp ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void web_fetch_rel_edu_extrato ( ref Communication var_Comm, bool ret , string output_st_csv, string output_st_total_periodo )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_REL_EDU_EXTRATO.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_REL_EDU_EXTRATO.st_total_periodo, output_st_total_periodo ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void web_fetch_resp_alunos ( ref Communication var_Comm, bool ret , string output_st_nomeResp, ArrayList output_array_generic_lst, ArrayList output_array_generic_lstMsg )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_RESP_ALUNOS.st_nomeResp, output_st_nomeResp ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
			DataPortable dp_array_generic_lstMsg = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_WEB_FETCH_RESP_ALUNOS.lst , ref output_array_generic_lst );
			dp_array_generic_lstMsg.MapTagArray ( COMM_OUT_WEB_FETCH_RESP_ALUNOS.lstMsg , ref output_array_generic_lstMsg );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
			var_Comm.AddExitPortable ( ref dp_array_generic_lstMsg );
		}
			
		public void web_exec_trocaLim ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_exec_alterSenhaEdu ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void schedule_batch ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void schedule_proc_batch ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void load_edu ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void type_load ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_edu_habilita ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_cartoes_grafica ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CARTOES_GRAFICA.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_edu_alteraDiario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_fetch_edu_virtual ( ref Communication var_Comm, bool ret , DadosCartaoEdu output_cont_dce, ArrayList output_array_generic_lst, ArrayList output_array_generic_lstEmp )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_WEB_FETCH_EDU_VIRTUAL.dce , output_cont_dce as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
			DataPortable dp_array_generic_lstEmp = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_WEB_FETCH_EDU_VIRTUAL.lst , ref output_array_generic_lst );
			dp_array_generic_lstEmp.MapTagArray ( COMM_OUT_WEB_FETCH_EDU_VIRTUAL.lstEmp , ref output_array_generic_lstEmp );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
			var_Comm.AddExitPortable ( ref dp_array_generic_lstEmp );
		}
			
		public void load_edu_emp_virtual ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void schedule_edu_fundo ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_fetch_edu_emp_hist ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_EDU_EMP_HIST.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void web_exec_edu_aplic_fundo ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_edu_cancelaCartao ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_edu_segundaVia ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_dadosAdministradora ( ref Communication var_Comm, bool ret , string output_st_in_csv, string output_st_out_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSADMINISTRADORA.st_in_csv, output_st_in_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSADMINISTRADORA.st_out_csv, output_st_out_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_alteraAdminEmpresa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_fetch_edu_ranking ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_FETCH_EDU_RANKING.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_conf_cartao ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_edu_nomeAluno ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_EDU_NOMEALUNO.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void load_legado ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_rel_5_rle ( ref Communication var_Comm, bool ret , string output_st_total, string output_st_total_cancelado, string output_st_csv_subtotal, string output_st_csv_subtotal_cancelado, string output_st_csv, string output_st_nome_empresa, ArrayList output_array_generic_lstLojas )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_total, output_st_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_total_cancelado, output_st_total_cancelado ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_csv_subtotal, output_st_csv_subtotal ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_csv_subtotal_cancelado, output_st_csv_subtotal_cancelado ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_5_RLE.st_nome_empresa, output_st_nome_empresa ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lstLojas = new DataPortable();
		
			dp_array_generic_lstLojas.MapTagArray ( COMM_OUT_FETCH_REL_5_RLE.lstLojas , ref output_array_generic_lstLojas );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstLojas );
		}
			
		public void exec_pos_desfazVendaEmpresarial ( ref Communication var_Comm, bool ret , string output_st_msg, POS_Resposta output_cont_pr )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_POS_DESFAZVENDAEMPRESARIAL.st_msg, output_st_msg ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_EXEC_POS_DESFAZVENDAEMPRESARIAL.pr , output_cont_pr as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void schedule_faturamento ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_dadosFaturamento ( ref Communication var_Comm, bool ret , string output_st_msg, string output_vr_valor )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSFATURAMENTO.st_msg, output_st_msg ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSFATURAMENTO.vr_valor, output_vr_valor ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void ins_despesa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_dadosDespesas ( ref Communication var_Comm, bool ret , string output_st_nome, ArrayList output_array_generic_list )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_DADOSDESPESAS.st_nome, output_st_nome ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_list = new DataPortable();
		
			dp_array_generic_list.MapTagArray ( COMM_OUT_FETCH_DADOSDESPESAS.list , ref output_array_generic_list );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_list );
		}
			
		public void exec_cancelaDespesa ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_rel_6_fat ( ref Communication var_Comm, bool ret , string output_st_total, string output_st_total_desconto, string output_st_csv_subtotal, string output_st_csv_subtotal_desconto, string output_st_content_block, string output_st_emp_loj_block, string output_CartaoAtiv, string output_Extras, string output_FixoTrans, string output_Percent, string output_TBM )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_total, output_st_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_total_desconto, output_st_total_desconto ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_csv_subtotal, output_st_csv_subtotal ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_csv_subtotal_desconto, output_st_csv_subtotal_desconto ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_content_block, output_st_content_block ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.st_emp_loj_block, output_st_emp_loj_block ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.CartaoAtiv, output_CartaoAtiv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.Extras, output_Extras ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.FixoTrans, output_FixoTrans ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.Percent, output_Percent ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_6_FAT.TBM, output_TBM ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_segundaVia ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_arquivoFat ( ref Communication var_Comm, bool ret , string output_st_msg, string output_nu_nsFat )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_ARQUIVOFAT.st_msg, output_st_msg ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_ARQUIVOFAT.nu_nsFat, output_nu_nsFat ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void upload_archive ( ref Communication var_Comm, bool ret , string output_st_new_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_UPLOAD_ARCHIVE.st_new_id, output_st_new_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_processaArqBancario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_relFat ( ref Communication var_Comm, bool ret , string output_st_total, string output_st_content_block )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_RELFAT.st_total, output_st_total ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_RELFAT.st_content_block, output_st_content_block ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_alteraProprietario ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_conveyUsuarios ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_CONVEYUSUARIOS.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_chamados ( ref Communication var_Comm, bool ret , string output_st_block )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CHAMADOS.st_block, output_st_block ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void ins_chamado ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_chamadoHist ( ref Communication var_Comm, bool ret , DadosChamado output_cont_dc, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_CHAMADOHIST.dc , output_cont_dc as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_CHAMADOHIST.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_alteraChamado ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_extraGift ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_EXTRAGIFT.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void ins_extraGift ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void del_extraGift ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_quiosque ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lstQ )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lstQ = new DataPortable();
		
			dp_array_generic_lstQ.MapTagArray ( COMM_OUT_FETCH_QUIOSQUE.lstQ , ref output_array_generic_lstQ );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstQ );
		}
			
		public void fetch_vendedorQuiosque ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lstVinc, ArrayList output_array_generic_lstOutros )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lstVinc = new DataPortable();
			DataPortable dp_array_generic_lstOutros = new DataPortable();
		
			dp_array_generic_lstVinc.MapTagArray ( COMM_OUT_FETCH_VENDEDORQUIOSQUE.lstVinc , ref output_array_generic_lstVinc );
			dp_array_generic_lstOutros.MapTagArray ( COMM_OUT_FETCH_VENDEDORQUIOSQUE.lstOutros , ref output_array_generic_lstOutros );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstVinc );
			var_Comm.AddExitPortable ( ref dp_array_generic_lstOutros );
		}
			
		public void exec_vincQuiosque ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void ins_quiosque ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void del_quiosque ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_comprov_Gift ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_COMPROV_GIFT.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_validGift ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_recargaGift ( ref Communication var_Comm, bool ret , string output_id_gift )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_RECARGAGIFT.id_gift, output_id_gift ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_consultaLojasGift ( ref Communication var_Comm, bool ret , string output_st_csv_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTALOJASGIFT.st_csv_id, output_st_csv_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_consultaCartaoGift ( ref Communication var_Comm, bool ret , string output_st_nome, string output_vr_disp, string output_st_sit, ArrayList output_array_generic_lstCred, ArrayList output_array_generic_lstProd, ArrayList output_array_generic_lstComprov )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.st_nome, output_st_nome ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.vr_disp, output_vr_disp ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.st_sit, output_st_sit ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lstCred = new DataPortable();
			DataPortable dp_array_generic_lstProd = new DataPortable();
			DataPortable dp_array_generic_lstComprov = new DataPortable();
		
			dp_array_generic_lstCred.MapTagArray ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.lstCred , ref output_array_generic_lstCred );
			dp_array_generic_lstProd.MapTagArray ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.lstProd , ref output_array_generic_lstProd );
			dp_array_generic_lstComprov.MapTagArray ( COMM_OUT_FETCH_CONSULTACARTAOGIFT.lstComprov , ref output_array_generic_lstComprov );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstCred );
			var_Comm.AddExitPortable ( ref dp_array_generic_lstProd );
			var_Comm.AddExitPortable ( ref dp_array_generic_lstComprov );
		}
			
		public void fetch_reciboVendaGift ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_RECIBOVENDAGIFT.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_proprietarioGift ( ref Communication var_Comm, bool ret , DadosProprietario output_cont_dp )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_PROPRIETARIOGIFT.dp , output_cont_dp as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void fetch_chequeGift ( ref Communication var_Comm, bool ret , string output_st_dados )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CHEQUEGIFT.st_dados, output_st_dados ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_compensaChequeGift ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_cancelaChequeGift ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_repasseData ( ref Communication var_Comm, bool ret , string output_block_detalhe_loja, string output_block_sumario_loja )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REPASSEDATA.block_detalhe_loja, output_block_detalhe_loja ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REPASSEDATA.block_sumario_loja, output_block_sumario_loja ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_repasseLoja ( ref Communication var_Comm, bool ret , string output_id_confRepasse )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_REPASSELOJA.id_confRepasse, output_id_confRepasse ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_convenioLojaGift ( ref Communication var_Comm, bool ret , string output_st_banco, string output_st_ag, string output_st_conta )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONVENIOLOJAGIFT.st_banco, output_st_banco ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONVENIOLOJAGIFT.st_ag, output_st_ag ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONVENIOLOJAGIFT.st_conta, output_st_conta ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_softwareVersion ( ref Communication var_Comm, bool ret , string output_st_versionOutdated )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_SOFTWAREVERSION.st_versionOutdated, output_st_versionOutdated ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void infra_fetchIncomingVersion ( ref Communication var_Comm, bool ret , string output_st_csv_files, string output_st_version )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_INFRA_FETCHINCOMINGVERSION.st_csv_files, output_st_csv_files ); 
			dp_out.MapTagValue ( COMM_OUT_INFRA_FETCHINCOMINGVERSION.st_version, output_st_version ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void infra_fetchFile ( ref Communication var_Comm, bool ret , string output_st_next_part, string output_st_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_INFRA_FETCHFILE.st_next_part, output_st_next_part ); 
			dp_out.MapTagValue ( COMM_OUT_INFRA_FETCHFILE.st_content, output_st_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void infra_fetchUpdaterVersion ( ref Communication var_Comm, bool ret , string output_st_csv_files )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_INFRA_FETCHUPDATERVERSION.st_csv_files, output_st_csv_files ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_rel_repEfetivo ( ref Communication var_Comm, bool ret , string output_st_csv_contents, string output_st_csv_pagto, string output_st_nome_empresa, string output_st_csv_lojas )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_REPEFETIVO.st_csv_contents, output_st_csv_contents ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_REPEFETIVO.st_csv_pagto, output_st_csv_pagto ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_REPEFETIVO.st_nome_empresa, output_st_nome_empresa ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_REPEFETIVO.st_csv_lojas, output_st_csv_lojas ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_consultaLojista ( ref Communication var_Comm, bool ret , string output_st_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTALOJISTA.st_content, output_st_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_rel_fechCaixa ( ref Communication var_Comm, bool ret , string output_st_csv_contents, string output_st_nome_empresa, ArrayList output_array_generic_lstQuiosques )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_FECHCAIXA.st_csv_contents, output_st_csv_contents ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_FECHCAIXA.st_nome_empresa, output_st_nome_empresa ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lstQuiosques = new DataPortable();
		
			dp_array_generic_lstQuiosques.MapTagArray ( COMM_OUT_FETCH_REL_FECHCAIXA.lstQuiosques , ref output_array_generic_lstQuiosques );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lstQuiosques );
		}
			
		public void ins_dependente ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_rel_dirCont ( ref Communication var_Comm, bool ret , string output_st_csv_contents, string output_st_nome_empresa, DadosSinteticoContGift output_cont_dsc )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_DIRCONT.st_csv_contents, output_st_csv_contents ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_DIRCONT.st_nome_empresa, output_st_nome_empresa ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_REL_DIRCONT.dsc , output_cont_dsc as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
		}
			
		public void fetch_codLoja ( ref Communication var_Comm, bool ret , string output_st_cod )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CODLOJA.st_cod, output_st_cod ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_reciboRepasse ( ref Communication var_Comm, bool ret , DadosRepRecibo output_cont_rec, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_cont_1 = new DataPortable();
		
			dp_cont_1.MapTagContainer ( COMM_OUT_FETCH_RECIBOREPASSE.rec , output_cont_rec as DataPortable );
		
			var_Comm.AddExitPortable ( ref dp_cont_1 ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_RECIBOREPASSE.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_resolvePend ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_empresasAfiliadas ( ref Communication var_Comm, bool ret , string output_st_nome_emp, ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_EMPRESASAFILIADAS.st_nome_emp, output_st_nome_emp ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_EMPRESASAFILIADAS.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_pos_buscaCartao ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_EXEC_POS_BUSCACARTAO.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_fat_recManual ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_empresasGrafica ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_EMPRESASGRAFICA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_bloq_loja ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_desbloq_loja ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_cancel_Loja ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void web_exec_confirmaBoleto ( ref Communication var_Comm, bool ret , string output_st_id )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_WEB_EXEC_CONFIRMABOLETO.st_id, output_st_id ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_user_lojista ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_USER_LOJISTA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_vincula_lojista ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_reciboVendaLojista ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_RECIBOVENDALOJISTA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_lojistaEmpresas ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_LOJISTAEMPRESAS.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void fetch_rel_prevLojista ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_PREVLOJISTA.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_rel_tarifas ( ref Communication var_Comm, bool ret , string output_st_csv, string output_st_csv_emp )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_TARIFAS.st_csv, output_st_csv ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_REL_TARIFAS.st_csv_emp, output_st_csv_emp ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void graph_financeiro ( ref Communication var_Comm, bool ret , string output_st_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_GRAPH_FINANCEIRO.st_content, output_st_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_listaTransacoesLojas ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_LISTATRANSACOESLOJAS.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void graph_transacoes ( ref Communication var_Comm, bool ret , string output_st_csv )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_GRAPH_TRANSACOES.st_csv, output_st_csv ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_pf_graficoGerencial ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_EXEC_PF_GRAFICOGERENCIAL.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_processaArqConvenio ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void fetch_consultaLojistaRep ( ref Communication var_Comm, bool ret , string output_st_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_CONSULTALOJISTAREP.st_content, output_st_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void exec_loginLojista ( ref Communication var_Comm, bool ret , string output_nome )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_LOGINLOJISTA.nome, output_nome ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_listawebConveniosLoja ( ref Communication var_Comm, bool ret , ArrayList output_array_generic_lst )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_array_generic_lst = new DataPortable();
		
			dp_array_generic_lst.MapTagArray ( COMM_OUT_FETCH_LISTAWEBCONVENIOSLOJA.lst , ref output_array_generic_lst );
		
			var_Comm.AddExitPortable ( ref dp_array_generic_lst );
		}
			
		public void exec_loginWeb ( ref Communication var_Comm, bool ret , string output_nome )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_EXEC_LOGINWEB.nome, output_nome ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_extratoWeb ( ref Communication var_Comm, bool ret , string output_st_content, string output_vr_disp, string output_vr_lim )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_EXTRATOWEB.st_content, output_st_content ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_EXTRATOWEB.vr_disp, output_vr_disp ); 
			dp_out.MapTagValue ( COMM_OUT_FETCH_EXTRATOWEB.vr_lim, output_vr_lim ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void fetch_edu_messages ( ref Communication var_Comm, bool ret , string output_st_content )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
			
			DataPortable dp_out = new DataPortable(); 
		
			dp_out.MapTagValue ( COMM_OUT_FETCH_EDU_MESSAGES.st_content, output_st_content ); 
		
			var_Comm.AddExitPortable ( ref dp_out ); 
		}
			
		public void ins_edu_msg ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void del_edu_msg ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
		public void exec_change_edu_msg ( ref Communication var_Comm, bool ret  )
		{
			var_Comm.Clear();
			var_Comm.m_TransactionSucessfull = ret;
		}
			
	}
	#endif
}
