// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosRepRecibo : DataPortable 
	{
		public const string loja = "loja";
		public const string cnpj = "cnpj";
		public const string pagto = "pagto";
		public const string vr_compras = "vr_compras";
		public const string tx_admin = "tx_admin";
		public const string vr_desc = "vr_desc";
		public const string vr_tot_rep = "vr_tot_rep";
		public const string st_extra = "st_extra";
		
		public DadosRepRecibo() { }
		
		public void Clear()
		{
			set_loja ( "" );
			set_cnpj ( "" );
			set_pagto ( "" );
			set_vr_compras ( "" );
			set_tx_admin ( "" );
			set_vr_desc ( "" );
			set_vr_tot_rep ( "" );
			set_st_extra ( "" );
		}
		
		public DadosRepRecibo ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_loja ( port.getValue ( loja ) );
			set_cnpj ( port.getValue ( cnpj ) );
			set_pagto ( port.getValue ( pagto ) );
			set_vr_compras ( port.getValue ( vr_compras ) );
			set_tx_admin ( port.getValue ( tx_admin ) );
			set_vr_desc ( port.getValue ( vr_desc ) );
			set_vr_tot_rep ( port.getValue ( vr_tot_rep ) );
			set_st_extra ( port.getValue ( st_extra ) );
		}
		
		public string get_loja () { return getValue ( loja ); }
		public string get_cnpj () { return getValue ( cnpj ); }
		public string get_pagto () { return getValue ( pagto ); }
		public string get_vr_compras () { return getValue ( vr_compras ); }
		public string get_tx_admin () { return getValue ( tx_admin ); }
		public string get_vr_desc () { return getValue ( vr_desc ); }
		public string get_vr_tot_rep () { return getValue ( vr_tot_rep ); }
		public string get_st_extra () { return getValue ( st_extra ); }
		
		public void set_loja ( string val ) { setValue ( loja , val ); }
		public void set_cnpj ( string val ) { setValue ( cnpj , val ); }
		public void set_pagto ( string val ) { setValue ( pagto , val ); }
		public void set_vr_compras ( string val ) { setValue ( vr_compras , val ); }
		public void set_tx_admin ( string val ) { setValue ( tx_admin , val ); }
		public void set_vr_desc ( string val ) { setValue ( vr_desc , val ); }
		public void set_vr_tot_rep ( string val ) { setValue ( vr_tot_rep , val ); }
		public void set_st_extra ( string val ) { setValue ( st_extra , val ); }
	}
}
