// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosAuditoria : DataPortable 
	{
		public const string dt_operacao = "dt_operacao";
		public const string st_usuario = "st_usuario";
		public const string nu_oper = "nu_oper";
		public const string st_obs = "st_obs";
		public const string id_link = "id_link";
		
		public DadosAuditoria() { }
		
		public void Clear()
		{
			set_dt_operacao ( "" );
			set_st_usuario ( "" );
			set_nu_oper ( "" );
			set_st_obs ( "" );
			set_id_link ( "" );
		}
		
		public DadosAuditoria ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_dt_operacao ( port.getValue ( dt_operacao ) );
			set_st_usuario ( port.getValue ( st_usuario ) );
			set_nu_oper ( port.getValue ( nu_oper ) );
			set_st_obs ( port.getValue ( st_obs ) );
			set_id_link ( port.getValue ( id_link ) );
		}
		
		public string get_dt_operacao () { return getValue ( dt_operacao ); }
		public string get_st_usuario () { return getValue ( st_usuario ); }
		public string get_nu_oper () { return getValue ( nu_oper ); }
		public string get_st_obs () { return getValue ( st_obs ); }
		public string get_id_link () { return getValue ( id_link ); }
		
		public void set_dt_operacao ( string val ) { setValue ( dt_operacao , val ); }
		public void set_st_usuario ( string val ) { setValue ( st_usuario , val ); }
		public void set_nu_oper ( string val ) { setValue ( nu_oper , val ); }
		public void set_st_obs ( string val ) { setValue ( st_obs , val ); }
		public void set_id_link ( string val ) { setValue ( id_link , val ); }
	}
}
