// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class POS_Entrada : DataPortable 
	{
		public const string st_empresa = "st_empresa";
		public const string st_matricula = "st_matricula";
		public const string st_titularidade = "st_titularidade";
		public const string st_senha = "st_senha";
		public const string st_terminal = "st_terminal";
        public const string st_terminalSITEF = "st_terminalSITEF";
        public const string vr_valor = "vr_valor";
		public const string nu_parcelas = "nu_parcelas";
		public const string st_valores = "st_valores";
		
		public POS_Entrada() { }
		
		public void Clear()
		{
			set_st_empresa ( "" );
			set_st_matricula ( "" );
			set_st_titularidade ( "" );
			set_st_senha ( "" );
			set_st_terminal ( "" );
            set_st_terminalSITEF("");
            set_vr_valor ( "" );
			set_nu_parcelas ( "" );
			set_st_valores ( "" );
		}
		
		public POS_Entrada ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_st_matricula ( port.getValue ( st_matricula ) );
			set_st_titularidade ( port.getValue ( st_titularidade ) );
			set_st_senha ( port.getValue ( st_senha ) );
			set_st_terminal ( port.getValue ( st_terminal ) );
            set_st_terminalSITEF (port.getValue(st_terminalSITEF));
            set_vr_valor ( port.getValue ( vr_valor ) );
			set_nu_parcelas ( port.getValue ( nu_parcelas ) );
			set_st_valores ( port.getValue ( st_valores ) );
		}
		
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_st_matricula () { return getValue ( st_matricula ); }
		public string get_st_titularidade () { return getValue ( st_titularidade ); }
		public string get_st_senha () { return getValue ( st_senha ); }
		public string get_st_terminal () { return getValue ( st_terminal ); }
        public string get_st_terminalSITEF() { return getValue(st_terminalSITEF); }
        public string get_vr_valor () { return getValue ( vr_valor ); }
		public string get_nu_parcelas () { return getValue ( nu_parcelas ); }
		public string get_st_valores () { return getValue ( st_valores ); }
		
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_st_matricula ( string val ) { setValue ( st_matricula , val ); }
		public void set_st_titularidade ( string val ) { setValue ( st_titularidade , val ); }
		public void set_st_senha ( string val ) { setValue ( st_senha , val ); }
		public void set_st_terminal ( string val ) { setValue ( st_terminal , val ); }
        public void set_st_terminalSITEF(string val) { setValue(st_terminalSITEF, val); }
        public void set_vr_valor ( string val ) { setValue ( vr_valor , val ); }
		public void set_nu_parcelas ( string val ) { setValue ( nu_parcelas , val ); }
		public void set_st_valores ( string val ) { setValue ( st_valores , val ); }
	}
}
