// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class CNetHeader : DataPortable 
	{
		public const string st_session = "st_session";
		public const string st_user_id = "st_user_id";
		public const string st_empresa = "st_empresa";
		public const string tg_user_type = "tg_user_type";
		public const string nu_terminal = "nu_terminal";
		
		public CNetHeader() { }
		
		public void Clear()
		{
			set_st_session ( "" );
			set_st_user_id ( "" );
			set_st_empresa ( "" );
			set_tg_user_type ( "" );
			set_nu_terminal ( "" );
		}
		
		public CNetHeader ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_session ( port.getValue ( st_session ) );
			set_st_user_id ( port.getValue ( st_user_id ) );
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_tg_user_type ( port.getValue ( tg_user_type ) );
			set_nu_terminal ( port.getValue ( nu_terminal ) );
		}
		
		public string get_st_session () { return getValue ( st_session ); }
		public string get_st_user_id () { return getValue ( st_user_id ); }
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_tg_user_type () { return getValue ( tg_user_type ); }
		public string get_nu_terminal () { return getValue ( nu_terminal ); }
		
		public void set_st_session ( string val ) { setValue ( st_session , val ); }
		public void set_st_user_id ( string val ) { setValue ( st_user_id , val ); }
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_tg_user_type ( string val ) { setValue ( tg_user_type , val ); }
		public void set_nu_terminal ( string val ) { setValue ( nu_terminal , val ); }
	}
}
