// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosNSU : DataPortable 
	{
		public const string vr_valor = "vr_valor";
		public const string st_nome = "st_nome";
		public const string st_cartao = "st_cartao";
		public const string dt_operacao = "dt_operacao";
		public const string st_terminal = "st_terminal";
		public const string st_empresa = "st_empresa";
		public const string st_matricula = "st_matricula";
		public const string st_titularidade = "st_titularidade";
		
		public DadosNSU() { }
		
		public void Clear()
		{
			set_vr_valor ( "" );
			set_st_nome ( "" );
			set_st_cartao ( "" );
			set_dt_operacao ( "" );
			set_st_terminal ( "" );
			set_st_empresa ( "" );
			set_st_matricula ( "" );
			set_st_titularidade ( "" );
		}
		
		public DadosNSU ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_vr_valor ( port.getValue ( vr_valor ) );
			set_st_nome ( port.getValue ( st_nome ) );
			set_st_cartao ( port.getValue ( st_cartao ) );
			set_dt_operacao ( port.getValue ( dt_operacao ) );
			set_st_terminal ( port.getValue ( st_terminal ) );
			set_st_empresa ( port.getValue ( st_empresa ) );
			set_st_matricula ( port.getValue ( st_matricula ) );
			set_st_titularidade ( port.getValue ( st_titularidade ) );
		}
		
		public string get_vr_valor () { return getValue ( vr_valor ); }
		public string get_st_nome () { return getValue ( st_nome ); }
		public string get_st_cartao () { return getValue ( st_cartao ); }
		public string get_dt_operacao () { return getValue ( dt_operacao ); }
		public string get_st_terminal () { return getValue ( st_terminal ); }
		public string get_st_empresa () { return getValue ( st_empresa ); }
		public string get_st_matricula () { return getValue ( st_matricula ); }
		public string get_st_titularidade () { return getValue ( st_titularidade ); }
		
		public void set_vr_valor ( string val ) { setValue ( vr_valor , val ); }
		public void set_st_nome ( string val ) { setValue ( st_nome , val ); }
		public void set_st_cartao ( string val ) { setValue ( st_cartao , val ); }
		public void set_dt_operacao ( string val ) { setValue ( dt_operacao , val ); }
		public void set_st_terminal ( string val ) { setValue ( st_terminal , val ); }
		public void set_st_empresa ( string val ) { setValue ( st_empresa , val ); }
		public void set_st_matricula ( string val ) { setValue ( st_matricula , val ); }
		public void set_st_titularidade ( string val ) { setValue ( st_titularidade , val ); }
	}
}
