// ###################################################### 
// ## SyCraf Engine Codegen                          #### 
// ###################################################### 
// ## This file is entirely written by               #### 
// ## the construction bot. DO NOT EDIT THIS FILE.   #### 
// ###################################################### 

using System;
using System.Collections;

namespace SyCrafEngine
{
	public class DadosExpedicao : DataPortable 
	{
		public const string st_line = "st_line";
		
		public DadosExpedicao() { }
		
		public void Clear()
		{
			set_st_line ( "" );
		}
		
		public DadosExpedicao ( DataPortable port ) 
		{
			Import ( port );
		}
		
		public override void Import ( DataPortable port ) 
		{
			set_st_line ( port.getValue ( st_line ) );
		}
		
		public string get_st_line () { return getValue ( st_line ); }
		
		public void set_st_line ( string val ) { setValue ( st_line , val ); }
	}
}
